In [1]:
import pandas as pd

In [4]:
abstracts_df = pd.read_csv(
    r"C:\Users\ercj\Desktop\plain_language_summarization_platform\final_abstracts\0218_combined_abstracts.csv",
    encoding="latin1"
)

final_df = pd.read_csv(
    r"C:\Users\ercj\Desktop\plain_language_summarization_platform\final_user_batches.csv",
    encoding="latin1"
)

In [12]:
REPLACE_COLS = [
    "question_1", "question_2", "question_4", "question_5",
    "question_1_answers_choices", "question_1_correct_answers",
    "question_2_answers_choices", "question_2_correct_answers",
    "question_4_answers_choices", "question_4_correct_answers",
    "question_5_answers_choices", "question_5_correct_answers",
]

# build a unique lookup from abstracts_df
abs_key = abstracts_df[["abstract_id"] + REPLACE_COLS].drop_duplicates(subset=["abstract_id"], keep="first")

# merge to pull the "correct" values
tmp = final_df[["abstract_id"]].merge(abs_key, on="abstract_id", how="left")

# sanity: any abstract_id missing in abstracts_df?
missing = tmp[REPLACE_COLS].isna().all(axis=1).sum()
print("Rows where abstract_id not found in abstracts_df:", int(missing))

# apply overwrite (Q3 untouched)
final_df_fixed = final_df.copy()
final_df_fixed[REPLACE_COLS] = tmp[REPLACE_COLS].to_numpy()

# ✅ write a NEW file with header (don't append)
out_path = r"C:\Users\ercj\Desktop\plain_language_summarization_platform\final_user_batches.csv"
final_df_fixed.to_csv(out_path, index=False, encoding="latin1")
print("Wrote:", out_path)

Rows where abstract_id not found in abstracts_df: 0
Wrote: C:\Users\ercj\Desktop\plain_language_summarization_platform\final_user_batches.csv

In [14]:
final_df = final_df_fixed

In [16]:
cols = [
    "question_1","question_2","question_3","question_4","question_5",
    "question_1_answers_choices","question_1_correct_answers",
    "question_2_answers_choices","question_2_correct_answers",
    "question_3_answers_choices","question_3_correct_answers",
    "question_4_answers_choices","question_4_correct_answers",
    "question_5_answers_choices","question_5_correct_answers",
]

subset = final_df[final_df["type"] == "static_2"]

def norm_df(df):
    return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

for aid in subset["abstract_id"].unique():
    expected = abstracts_df.loc[abstracts_df["abstract_id"] == aid, ["abstract_id"] + cols].drop_duplicates("abstract_id")
    actual   = subset.loc[subset["abstract_id"] == aid, ["abstract_id"] + cols].drop_duplicates()

    expected_norm = norm_df(expected[cols])
    actual_norm   = norm_df(actual[cols])

    if not expected_norm.equals(actual_norm):
        print("\n==============================")
        print(f"ABSTRACT ID: {aid}")
        print("EXPECTED (from abstracts_df):")
        display(expected)

        print("ACTUAL UNIQUE ROWS (from final_df static_2):")
        display(actual)

==============================
ABSTRACT ID: 1089
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
80,1089,What condition does sickle cell disease primar...,Identify a key characteristic of red blood cel...,Select the items that are animals,What is the main purpose of the reviewed trial...,What serious kidney complication can arise fro...,Red blood cells; White blood cells; Blood plat...,Red blood cells,Flexible and disc-shaped; Rigid and crescent-s...,Rigid and crescent-shaped,Chair; Lamp; Dog,Dog,To prevent kidney protein leak; To slow kidney...,To slow kidney function decline,Kidney stones; Need for dialysis or kidney tra...,Need for dialysis or kidney transplant

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
1,1089,What condition does sickle cell disease primar...,Identify a key characteristic of red blood cel...,Select the items that are animals,What is the main purpose of the reviewed trial...,What serious kidney complication can arise fro...,Red blood cells; White blood cells; Blood plat...,Red blood cells,Flexible and disc-shaped; Rigid and crescent-s...,Rigid and crescent-shaped,Chair; Lamp; Dog,Dog,To prevent kidney protein leak; To slow kidney...,To slow kidney function decline,Kidney stones; Need for dialysis or kidney tra...,Need for dialysis or kidney transplant

==============================
ABSTRACT ID: 1072
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
64,1072,"Based on study outcomes, which strategies best...",What was the main goal of including action pla...,Select all of the following that are colors,What was the effect of self-management interve...,How did the self-management interventions affe...,Monitoring respiratory-related hospital admiss...,Monitoring respiratory-related hospital admiss...,To motivate and support patients; To cure COPD...,To motivate and support patients,blue; green; pink,blue; green; pink,A reduction in hospital admissions; An increas...,A reduction in hospital admissions,There was a small increase in respiratory-rela...,There was a small increase in respiratory-rela...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
2,1072,"Based on study outcomes, which strategies best...",What was the main goal of including action pla...,Select all of the following that are colors,What was the effect of self-management interve...,How did the self-management interventions affe...,Monitoring respiratory-related hospital admiss...,Monitoring respiratory-related hospital admiss...,To motivate and support patients; To cure COPD...,To motivate and support patients,blue; green; pink,blue; green; pink,A reduction in hospital admissions; An increas...,A reduction in hospital admissions,There was a small increase in respiratory-rela...,There was a small increase in respiratory-rela...
128,1072,"Based on study outcomes, which strategies best...",What was the main goal of including action pla...,Select all of the following that are fruits,What was the effect of self-management interve...,How did the self-management interventions affe...,Monitoring respiratory-related hospital admiss...,Monitoring respiratory-related hospital admiss...,To motivate and support patients; To cure COPD...,To motivate and support patients,dog; blue; grape,grape,A reduction in hospital admissions; An increas...,A reduction in hospital admissions,There was a small increase in respiratory-rela...,There was a small increase in respiratory-rela...

==============================
ABSTRACT ID: 1036
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
31,1036,Contrast the potential impact of NOACs on all-...,How might rivaroxaban's potential to increase ...,Select all of the following that are fruits,What is the study primarily evaluating in peop...,In people without a medical reason for blood t...,NOACs appear more beneficial for individuals w...,NOACs appear more beneficial for individuals w...,It may lead clinicians to prefer antiplatelet ...,It may lead clinicians to prefer antiplatelet ...,dog; blue; grape,grape,The efficacy and safety of NOACs; The cost-eff...,The efficacy and safety of NOACs,They may increase the risk of death; They show...,They may increase the risk of death

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
10,1036,Contrast the potential impact of NOACs on all-...,How might rivaroxaban's potential to increase ...,Select all of the following that are fruits,What is the study primarily evaluating in peop...,In people without a medical reason for blood t...,NOACs appear more beneficial for individuals w...,NOACs appear more beneficial for individuals w...,It may lead clinicians to prefer antiplatelet ...,It may lead clinicians to prefer antiplatelet ...,dog; blue; grape,grape,The efficacy and safety of NOACs; The cost-eff...,The efficacy and safety of NOACs,They may increase the risk of death; They show...,They may increase the risk of death

==============================
ABSTRACT ID: 1086
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
77,1086,What is primary membranous nephropathy (PMN) p...,"In the context of PMN, what does spontaneous r...",Select all of the following that are fruits,Which type of PMN patients might require immun...,What is a primary goal of immunosuppressive th...,An autoimmune attack on the kidneys; A viral i...,An autoimmune attack on the kidneys,The disease resolves by itself; Immediate need...,The disease resolves by itself,dog; blue; grape,grape,Patients with spontaneous complete remission; ...,Patients with severe or worsening PMN,To reduce the progression to end-stage kidney ...,To reduce the progression to end-stage kidney ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
11,1086,What is primary membranous nephropathy (PMN) p...,"In the context of PMN, what does spontaneous r...",Select the items that are articles of clothing,Which type of PMN patients might require immun...,What is a primary goal of immunosuppressive th...,An autoimmune attack on the kidneys; A viral i...,An autoimmune attack on the kidneys,The disease resolves by itself; Immediate need...,The disease resolves by itself,shirt; jeans; jacket,shirt; jeans; jacket,Patients with spontaneous complete remission; ...,Patients with severe or worsening PMN,To reduce the progression to end-stage kidney ...,To reduce the progression to end-stage kidney ...
244,1086,What is primary membranous nephropathy (PMN) p...,"In the context of PMN, what does spontaneous r...",Select all of the following that are fruits,Which type of PMN patients might require immun...,What is a primary goal of immunosuppressive th...,An autoimmune attack on the kidneys; A viral i...,An autoimmune attack on the kidneys,The disease resolves by itself; Immediate need...,The disease resolves by itself,dog; blue; grape,grape,Patients with spontaneous complete remission; ...,Patients with severe or worsening PMN,To reduce the progression to end-stage kidney ...,To reduce the progression to end-stage kidney ...

==============================
ABSTRACT ID: 1006
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
4,1006,What key factors led the researchers to choose...,How do the results of GLP-1 agonists in compar...,Select all of the following that are fruits,Which findings regarding side effects would mo...,What is the primary purpose of glucagon-like p...,Their mechanism of stimulating glucose-depende...,Their mechanism of stimulating glucose-depende...,They ensure GLP-1 agonists will replace all ot...,They provide evidence supporting the inclusion...,dog; blue; grape,grape,The persistence of gastrointestinal effects li...,The decrease in hypoglycemic events compared t...,To reduce blood glucose levels; To replace ins...,To reduce blood glucose levels

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
19,1006,What key factors led the researchers to choose...,How do the results of GLP-1 agonists in compar...,Select all of the following that are fruits,Which findings regarding side effects would mo...,What is the primary purpose of glucagon-like p...,Their mechanism of stimulating glucose-depende...,Their mechanism of stimulating glucose-depende...,They ensure GLP-1 agonists will replace all ot...,They provide evidence supporting the inclusion...,dog; blue; grape,grape,The persistence of gastrointestinal effects li...,The decrease in hypoglycemic events compared t...,To reduce blood glucose levels; To replace ins...,To reduce blood glucose levels

==============================
ABSTRACT ID: 1045
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
39,1045,How might the risk of bias in trials impact th...,What rationale can be evaluated for not suppor...,Select all of the following that are fruits,What was the primary aim of the Cochrane syste...,What was the result of the meta-analyses at ma...,They could overestimate the beneficial effects...,They could overestimate the beneficial effects...,Evidence indicates potential harm in terms of ...,Evidence indicates potential harm in terms of ...,dog; blue; grape,grape,To assess the benefits and harms of antibiotic...,To assess the benefits and harms of antibiotic...,Antibiotics increased the risk of all-cause mo...,Antibiotics increased the risk of all-cause mo...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
20,1045,How might the risk of bias in trials impact th...,What rationale can be evaluated for not suppor...,Select the items that are articles of clothing,What was the primary aim of the Cochrane syste...,What was the result of the meta-analyses at ma...,They could overestimate the beneficial effects...,They could overestimate the beneficial effects...,Evidence indicates potential harm in terms of ...,Evidence indicates potential harm in terms of ...,shirt; jeans; jacket,shirt; jeans; jacket,To assess the benefits and harms of antibiotic...,To assess the benefits and harms of antibiotic...,Antibiotics increased the risk of all-cause mo...,Antibiotics increased the risk of all-cause mo...

==============================
ABSTRACT ID: 1111
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
100,1111,What can be deduced about the effectiveness of...,What criteria can be used to evaluate the reli...,Select all of the following that are fruits,What are the implications of the studyÃ¢ÂÂs ...,How could the limited findings on harms associ...,Masks show consistent effectiveness across all...,Effectiveness of masks is inconsistent across ...,The number of trials and participants involved...,The number of trials and participants involved...,dog; blue; grape,grape,Designing trials with a focus on heterogeneous...,Designing trials with a focus on heterogeneous...,Policies may proceed cautiously due to potenti...,Policies may proceed cautiously due to potenti...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
28,1111,What can be deduced about the effectiveness of...,What criteria can be used to evaluate the reli...,Select all of the following that are fruits,What are the implications of the studyÃ¢ÂÂs ...,How could the limited findings on harms associ...,Masks show consistent effectiveness across all...,Effectiveness of masks is inconsistent across ...,The number of trials and participants involved...,The number of trials and participants involved...,dog; blue; grape,grape,Designing trials with a focus on heterogeneous...,Designing trials with a focus on heterogeneous...,Policies may proceed cautiously due to potenti...,Policies may proceed cautiously due to potenti...
326,1111,What can be deduced about the effectiveness of...,What criteria can be used to evaluate the reli...,Select the items that are articles of clothing,What are the implications of the studyÃ¢ÂÂs ...,How could the limited findings on harms associ...,Masks show consistent effectiveness across all...,Effectiveness of masks is inconsistent across ...,The number of trials and participants involved...,The number of trials and participants involved...,shirt; jeans; jacket,shirt; jeans; jacket,Designing trials with a focus on heterogeneous...,Designing trials with a focus on heterogeneous...,Policies may proceed cautiously due to potenti...,Policies may proceed cautiously due to potenti...

==============================
ABSTRACT ID: 1020
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
16,1020,Critically assess why the study concludes that...,What was the primary focus of the study regard...,Select all of the following that are fruits,Which EGFR-targeted drugs were found to delay ...,What outcome was specifically associated with ...,TKIs are shown to delay cancer progression and...,TKIs are shown to delay cancer progression and...,To determine if EGFR-targeted drugs improve pr...,To determine if EGFR-targeted drugs improve pr...,dog; blue; grape,grape,Erlotinib; Gefitinib; Cetuximab,Erlotinib; Gefitinib,They improved health-related quality of life; ...,They improved health-related quality of life

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
29,1020,Critically assess why the study concludes that...,What was the primary focus of the study regard...,Select the items that are articles of clothing,Which EGFR-targeted drugs were found to delay ...,What outcome was specifically associated with ...,TKIs are shown to delay cancer progression and...,TKIs are shown to delay cancer progression and...,To determine if EGFR-targeted drugs improve pr...,To determine if EGFR-targeted drugs improve pr...,shirt; jeans; jacket,shirt; jeans; jacket,Erlotinib; Gefitinib; Cetuximab,Erlotinib; Gefitinib,They improved health-related quality of life; ...,They improved health-related quality of life
56,1020,Critically assess why the study concludes that...,What was the primary focus of the study regard...,Select all of the following that are fruits,Which EGFR-targeted drugs were found to delay ...,What outcome was specifically associated with ...,TKIs are shown to delay cancer progression and...,TKIs are shown to delay cancer progression and...,To determine if EGFR-targeted drugs improve pr...,To determine if EGFR-targeted drugs improve pr...,dog; blue; grape,grape,Erlotinib; Gefitinib; Cetuximab,Erlotinib; Gefitinib,They improved health-related quality of life; ...,They improved health-related quality of life

==============================
ABSTRACT ID: 1104
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
93,1104,Critique the limitations of this review in ter...,What conclusions can be deduced about the impa...,Select all of the following that are colors,Summarize the impact of implementation strateg...,Explain the role of opinion leaders in the imp...,The review missed studies due to inconsistent ...,The review missed studies due to inconsistent ...,They likely lead to significant improvements i...,They do not significantly impact children's di...,blue; green; pink,blue; green; pink,They do not appear to have an impact on physic...,They do not appear to have an impact on physic...,They provided financial support for equipment;...,They helped promote and guide policy implement...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
37,1104,Critique the limitations of this review in ter...,What conclusions can be deduced about the impa...,Select all of the following that are colors,Summarize the impact of implementation strateg...,Explain the role of opinion leaders in the imp...,The review missed studies due to inconsistent ...,The review missed studies due to inconsistent ...,They likely lead to significant improvements i...,They do not significantly impact children's di...,blue; green; pink,blue; green; pink,They do not appear to have an impact on physic...,They do not appear to have an impact on physic...,They provided financial support for equipment;...,They helped promote and guide policy implement...
271,1104,Critique the limitations of this review in ter...,What conclusions can be deduced about the impa...,Select the items that are animals,Summarize the impact of implementation strateg...,Explain the role of opinion leaders in the imp...,The review missed studies due to inconsistent ...,The review missed studies due to inconsistent ...,They likely lead to significant improvements i...,They do not significantly impact children's di...,Chair; Lamp; Dog,Dog,They do not appear to have an impact on physic...,They do not appear to have an impact on physic...,They provided financial support for equipment;...,They helped promote and guide policy implement...
937,1104,Critique the limitations of this review in ter...,What conclusions can be deduced about the impa...,Select the items that are articles of clothing,Summarize the impact of implementation strateg...,Explain the role of opinion leaders in the imp...,The review missed studies due to inconsistent ...,The review missed studies due to inconsistent ...,They likely lead to significant improvements i...,They do not significantly impact children's di...,shirt; jeans; jacket,shirt; jeans; jacket,They do not appear to have an impact on physic...,They do not appear to have an impact on physic...,They provided financial support for equipment;...,They helped promote and guide policy implement...

==============================
ABSTRACT ID: 1120
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
107,1120,What inference can be made about the populatio...,How does the review suggest doctors should nav...,Select all of the following that are fruits,What conclusion can be drawn about the compara...,"In the review, which antidepressant was examin...",Populations with a yearly recurrence rate of 6...,Populations with a yearly recurrence rate of 60%.,By prioritizing drugs like bupropion XL over a...,By heavily considering patient preferences in ...,dog; blue; grape,grape,Bupropion XL is the only SGA proven to prevent...,There is insufficient evidence to compare bupr...,Fluoxetine; Bupropion extended-release; Sertra...,Bupropion extended-release

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
38,1120,What inference can be made about the populatio...,How does the review suggest doctors should nav...,Select all of the following that are fruits,What conclusion can be drawn about the compara...,"In the review, which antidepressant was examin...",Populations with a yearly recurrence rate of 6...,Populations with a yearly recurrence rate of 60%.,By prioritizing drugs like bupropion XL over a...,By heavily considering patient preferences in ...,dog; blue; grape,grape,Bupropion XL is the only SGA proven to prevent...,There is insufficient evidence to compare bupr...,Fluoxetine; Bupropion extended-release; Sertra...,Bupropion extended-release

==============================
ABSTRACT ID: 1050
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
43,1050,What underlying motivations drive the study's ...,How do the study's findings contribute to the ...,Select all of the following that are fruits,What hypothesis could be formulated about omeg...,Describe the evidence about the influence of o...,To assess whether omega-6 fats affect energy p...,To investigate whether increasing omega-6 fats...,They provide conclusive evidence supporting om...,They highlight the uncertainty in omega-6 fats...,dog; blue; grape,grape,Omega-6 fats may provide significant long-term...,Higher-quality evidence is needed to substanti...,There is no conclusive evidence of benefit or ...,There is no conclusive evidence of benefit or ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
47,1050,What underlying motivations drive the study's ...,How do the study's findings contribute to the ...,Select the items that are articles of clothing,What hypothesis could be formulated about omeg...,Describe the evidence about the influence of o...,To assess whether omega-6 fats affect energy p...,To investigate whether increasing omega-6 fats...,They provide conclusive evidence supporting om...,They highlight the uncertainty in omega-6 fats...,shirt; jeans; jacket,shirt; jeans; jacket,Omega-6 fats may provide significant long-term...,Higher-quality evidence is needed to substanti...,There is no conclusive evidence of benefit or ...,There is no conclusive evidence of benefit or ...
343,1050,What underlying motivations drive the study's ...,How do the study's findings contribute to the ...,Select all of the following that are fruits,What hypothesis could be formulated about omeg...,Describe the evidence about the influence of o...,To assess whether omega-6 fats affect energy p...,To investigate whether increasing omega-6 fats...,They provide conclusive evidence supporting om...,They highlight the uncertainty in omega-6 fats...,dog; blue; grape,grape,Omega-6 fats may provide significant long-term...,Higher-quality evidence is needed to substanti...,There is no conclusive evidence of benefit or ...,There is no conclusive evidence of benefit or ...

==============================
ABSTRACT ID: 1056
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
48,1056,What were the motivations for the study's focu...,Which factors contributed to the uncertainty o...,Select all of the following that are colors,"Based on the study, what can be concluded abou...",Explain the main goal of the study in your own...,Elevated body temperatures suggest potentially...,Elevated body temperatures suggest potentially...,The study used a too short duration of treatme...,The small sample size and lack of pre-planned ...,blue; green; pink,blue; green; pink,The study provides strong evidence that coolin...,Cooling methods' impact on mortality is uncert...,To determine if cooling to 35-37.5Â°C improves...,To determine if cooling to 35-37.5Â°C improves...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
55,1056,What were the motivations for the study's focu...,Which factors contributed to the uncertainty o...,Select all of the following that are colors,"Based on the study, what can be concluded abou...",Explain the main goal of the study in your own...,Elevated body temperatures suggest potentially...,Elevated body temperatures suggest potentially...,The study used a too short duration of treatme...,The small sample size and lack of pre-planned ...,blue; green; pink,blue; green; pink,The study provides strong evidence that coolin...,Cooling methods' impact on mortality is uncert...,To determine if cooling to 35-37.5Â°C improves...,To determine if cooling to 35-37.5Â°C improves...

==============================
ABSTRACT ID: 1023
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
19,1023,What are the underlying motivations for focusi...,How did the study distinguish between the effe...,Select the items that are animals,Critique the robustness of the studyÃ¢ÂÂs co...,What is the primary aim of the study discussed...,"They often tolerate treatment well, similar to...",They represent a significant but often neglect...,It demonstrated improved survival outcomes wit...,It demonstrated improved survival outcomes wit...,Chair; Lamp; Dog,Dog,The study robustly proves the superiority of i...,The evidence for the efficacy of immunotherapy...,To find the best therapy for people with PS 2 ...,To find the best therapy for people with PS 2 ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
64,1023,What are the underlying motivations for focusi...,How did the study distinguish between the effe...,Select the items that are animals,Critique the robustness of the studyÃ¢ÂÂs co...,What is the primary aim of the study discussed...,"They often tolerate treatment well, similar to...",They represent a significant but often neglect...,It demonstrated improved survival outcomes wit...,It demonstrated improved survival outcomes wit...,Chair; Lamp; Dog,Dog,The study robustly proves the superiority of i...,The evidence for the efficacy of immunotherapy...,To find the best therapy for people with PS 2 ...,To find the best therapy for people with PS 2 ...

==============================
ABSTRACT ID: 1085
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
76,1085,Name a motivation for the study according to t...,State a key finding regarding the duration of ...,Select the items that are animals,Explain the goal of reviewing different steroi...,Paraphrase the study's conclusion on treatment...,To find the most effective steroid regimens; T...,To find the most effective steroid regimens,Longer courses reduce the chance of episodes; ...,Shorter courses are as effective as longer cou...,Chair; Lamp; Dog,Dog,To balance efficacy and side effects; To elimi...,To balance efficacy and side effects,Extending treatment beyond two to three months...,Extending treatment beyond two to three months...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
73,1085,Name a motivation for the study according to t...,State a key finding regarding the duration of ...,Select the items that are animals,Explain the goal of reviewing different steroi...,Paraphrase the study's conclusion on treatment...,To find the most effective steroid regimens; T...,To find the most effective steroid regimens,Longer courses reduce the chance of episodes; ...,Shorter courses are as effective as longer cou...,Chair; Lamp; Dog,Dog,To balance efficacy and side effects; To elimi...,To balance efficacy and side effects,Extending treatment beyond two to three months...,Extending treatment beyond two to three months...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1013
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
10,1013,"Given the study's results, how would you judge...",What can be inferred about the need for additi...,Select all of the following that are colors,Identify which exercise types were compared in...,What was one of the primary outcomes measured ...,Resistance training is conclusively more effec...,The evidence is too uncertain to favor one typ...,There is a need for larger studies to clarify ...,There is a need for larger studies to clarify ...,blue; green; pink,blue; green; pink,Cardiovascular and resistance training; Yoga a...,Cardiovascular and resistance training,Cancer-related fatigue; Nutritional intake; Sl...,Cancer-related fatigue

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
74,1013,"Given the study's results, how would you judge...",What can be inferred about the need for additi...,Select all of the following that are colors,Identify which exercise types were compared in...,What was one of the primary outcomes measured ...,Resistance training is conclusively more effec...,The evidence is too uncertain to favor one typ...,There is a need for larger studies to clarify ...,There is a need for larger studies to clarify ...,blue; green; pink,blue; green; pink,Cardiovascular and resistance training; Yoga a...,Cardiovascular and resistance training,Cancer-related fatigue; Nutritional intake; Sl...,Cancer-related fatigue
704,1013,"Given the study's results, how would you judge...",What can be inferred about the need for additi...,Select the items that are articles of clothing,Identify which exercise types were compared in...,What was one of the primary outcomes measured ...,Resistance training is conclusively more effec...,The evidence is too uncertain to favor one typ...,There is a need for larger studies to clarify ...,There is a need for larger studies to clarify ...,shirt; jeans; jacket,shirt; jeans; jacket,Cardiovascular and resistance training; Yoga a...,Cardiovascular and resistance training,Cancer-related fatigue; Nutritional intake; Sl...,Cancer-related fatigue

==============================
ABSTRACT ID: 1058
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
50,1058,What criteria could be used to judge the effic...,What does RDAT stand for in the context of wor...,Select all of the following that are fruits,What was the observed relationship between the...,"According to the summary, what is one potentia...",The reduction in reported property damage inci...,The reduction in reported property damage inci...,Random Drug and Alcohol Testing; Routine Daily...,Random Drug and Alcohol Testing,dog; blue; grape,grape,A higher percentage of workers tested was asso...,A higher percentage of workers tested was asso...,To deter inappropriate use of substances among...,To deter inappropriate use of substances among...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
82,1058,What criteria could be used to judge the effic...,What does RDAT stand for in the context of wor...,Select the items that are articles of clothing,What was the observed relationship between the...,"According to the summary, what is one potentia...",The reduction in reported property damage inci...,The reduction in reported property damage inci...,Random Drug and Alcohol Testing; Routine Daily...,Random Drug and Alcohol Testing,shirt; jeans; jacket,shirt; jeans; jacket,A higher percentage of workers tested was asso...,A higher percentage of workers tested was asso...,To deter inappropriate use of substances among...,To deter inappropriate use of substances among...

==============================
ABSTRACT ID: 1060
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
52,1060,What types of disabilities can traumatic physi...,Identify the primary purpose of evaluating psy...,Select all of the following that are colors,Which psychosocial intervention showed short-t...,Explain the overall finding regarding the effe...,Physical and mental health problems; Improved ...,Physical and mental health problems,To prevent adverse secondary outcomes; To redu...,To prevent adverse secondary outcomes,blue; green; pink,blue; green; pink,Collaborative care intervention; Self-help boo...,Collaborative care intervention,No convincing evidence supports their efficacy...,No convincing evidence supports their efficacy

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
91,1060,What types of disabilities can traumatic physi...,Identify the primary purpose of evaluating psy...,Select all of the following that are colors,Which psychosocial intervention showed short-t...,Explain the overall finding regarding the effe...,Physical and mental health problems; Improved ...,Physical and mental health problems,To prevent adverse secondary outcomes; To redu...,To prevent adverse secondary outcomes,blue; green; pink,blue; green; pink,Collaborative care intervention; Self-help boo...,Collaborative care intervention,No convincing evidence supports their efficacy...,No convincing evidence supports their efficacy
101,1060,What types of disabilities can traumatic physi...,Identify the primary purpose of evaluating psy...,Select the items that are articles of clothing,Which psychosocial intervention showed short-t...,Explain the overall finding regarding the effe...,Physical and mental health problems; Improved ...,Physical and mental health problems,To prevent adverse secondary outcomes; To redu...,To prevent adverse secondary outcomes,shirt; jeans; jacket,shirt; jeans; jacket,Collaborative care intervention; Self-help boo...,Collaborative care intervention,No convincing evidence supports their efficacy...,No convincing evidence supports their efficacy

==============================
ABSTRACT ID: 1014
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
11,1014,What factors were examined to assess study qua...,What is the potential impact of yoga on medium...,Select the items that are animals,What was the primary focus of the study review...,What uncertainty is highlighted in the evidenc...,"Type of yoga, format of exercise, and particip...","Type of yoga, format of exercise, and particip...",The impact is unclear due to very uncertain ev...,The impact is unclear due to very uncertain ev...,Chair; Lamp; Dog,Dog,To compare the effects of different types of y...,To assess the impact of yoga on cancer-related...,No studies assessed long-term quality of life;...,No studies assessed long-term quality of life

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
92,1014,What factors were examined to assess study qua...,What is the potential impact of yoga on medium...,Select the items that are animals,What was the primary focus of the study review...,What uncertainty is highlighted in the evidenc...,"Type of yoga, format of exercise, and particip...","Type of yoga, format of exercise, and particip...",The impact is unclear due to very uncertain ev...,The impact is unclear due to very uncertain ev...,Chair; Lamp; Dog,Dog,To compare the effects of different types of y...,To assess the impact of yoga on cancer-related...,No studies assessed long-term quality of life;...,No studies assessed long-term quality of life

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1128
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
113,1128,"In terms of study design, how could future inv...",What conclusions can be drawn about the benefi...,Select all of the following that are colors,What is the main purpose of using rivastigmine...,Summarize the main findings regarding the effi...,Include more diverse patient populations for b...,Include more diverse patient populations for b...,Rivastigmine leads to significant improvements...,There are no observable differences between ri...,blue; green; pink,blue; green; pink,To cure Alzheimer's disease; To alleviate symp...,To alleviate symptoms of dementia,Rivastigmine significantly improved cognitive ...,Rivastigmine significantly improved cognitive ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
100,1128,"In terms of study design, how could future inv...",What conclusions can be drawn about the benefi...,Select all of the following that are colors,What is the main purpose of using rivastigmine...,Summarize the main findings regarding the effi...,Include more diverse patient populations for b...,Include more diverse patient populations for b...,Rivastigmine leads to significant improvements...,There are no observable differences between ri...,blue; green; pink,blue; green; pink,To cure Alzheimer's disease; To alleviate symp...,To alleviate symptoms of dementia,Rivastigmine significantly improved cognitive ...,Rivastigmine significantly improved cognitive ...

==============================
ABSTRACT ID: 1034
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
29,1034,In what ways did the methodological difference...,"Based on the evidence provided, how would you ...",Select all of the following that are colors,What does coenzyme Q10 aim to address in heart...,"According to the review, what is a potential e...",Variations in study design may introduce bias;...,Variations in study design may introduce bias;...,Moderately promising due to reduced mortality ...,Moderately promising due to reduced mortality ...,blue; green; pink,blue; green; pink,Increase cardiac output; Reduce the harmful ef...,Reduce the harmful effects of reactive oxygen ...,It probably reduces the risk; It definitely in...,It probably reduces the risk

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
110,1034,In what ways did the methodological difference...,"Based on the evidence provided, how would you ...",Select all of the following that are fruits,What does coenzyme Q10 aim to address in heart...,"According to the review, what is a potential e...",Variations in study design may introduce bias;...,Variations in study design may introduce bias;...,Moderately promising due to reduced mortality ...,Moderately promising due to reduced mortality ...,dog; blue; grape,grape,Increase cardiac output; Reduce the harmful ef...,Reduce the harmful effects of reactive oxygen ...,It probably reduces the risk; It definitely in...,It probably reduces the risk
469,1034,In what ways did the methodological difference...,"Based on the evidence provided, how would you ...",Select all of the following that are colors,What does coenzyme Q10 aim to address in heart...,"According to the review, what is a potential e...",Variations in study design may introduce bias;...,Variations in study design may introduce bias;...,Moderately promising due to reduced mortality ...,Moderately promising due to reduced mortality ...,blue; green; pink,blue; green; pink,Increase cardiac output; Reduce the harmful ef...,Reduce the harmful effects of reactive oxygen ...,It probably reduces the risk; It definitely in...,It probably reduces the risk

==============================
ABSTRACT ID: 1078
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
69,1078,How do the various interventions compare in th...,What was the primary purpose of the study disc...,Select all of the following that are fruits,How did the seasonal omalizumab treatment affe...,What problem is associated with the increase o...,Omalizumab proved more effective than leukotri...,Omalizumab proved more effective than leukotri...,To assess the effects of pre-autumn interventi...,To assess the effects of pre-autumn interventi...,dog; blue; grape,grape,Reduced exacerbations by 11%; Reduced exacerba...,Reduced exacerbations to 11% of occurrences,Increased contact with triggers such as viruse...,Increased contact with triggers such as viruses

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
118,1078,How do the various interventions compare in th...,What was the primary purpose of the study disc...,Select all of the following that are fruits,How did the seasonal omalizumab treatment affe...,What problem is associated with the increase o...,Omalizumab proved more effective than leukotri...,Omalizumab proved more effective than leukotri...,To assess the effects of pre-autumn interventi...,To assess the effects of pre-autumn interventi...,dog; blue; grape,grape,Reduced exacerbations by 11%; Reduced exacerba...,Reduced exacerbations to 11% of occurrences,Increased contact with triggers such as viruse...,Increased contact with triggers such as viruses

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1053
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
45,1053,How might the lack of randomized controlled tr...,What is the intended benefit of adding mydriat...,Select the items that are animals,Describe the condition known as traumatic irid...,What standard treatment is used for traumatic ...,Clinicians may hesitate to use mydriatics due ...,Clinicians may hesitate to use mydriatics due ...,To relieve pain and improve vision; To reduce ...,To relieve pain and improve vision,Chair; Lamp; Dog,Dog,An inflammation of the iris and ciliary body; ...,An inflammation of the iris and ciliary body,Anti-inflammatory eye drops (corticosteroids);...,Anti-inflammatory eye drops (corticosteroids)

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
119,1053,How might the lack of randomized controlled tr...,What is the intended benefit of adding mydriat...,Select the items that are animals,Describe the condition known as traumatic irid...,What standard treatment is used for traumatic ...,Clinicians may hesitate to use mydriatics due ...,Clinicians may hesitate to use mydriatics due ...,To relieve pain and improve vision; To reduce ...,To relieve pain and improve vision,Chair; Lamp; Dog,Dog,An inflammation of the iris and ciliary body; ...,An inflammation of the iris and ciliary body,Anti-inflammatory eye drops (corticosteroids);...,Anti-inflammatory eye drops (corticosteroids)

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1033
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
28,1033,How do case management interventions compare w...,What were the primary motivations for explorin...,Select all of the following that are colors,How does the study describe the effect of mult...,Identify the populations studied in the trials...,Case management may reduce all-cause mortality...,Case management may reduce all-cause mortality.,To provide ongoing support rather than crisis ...,To provide ongoing support rather than crisis ...,blue; green; pink,blue; green; pink,They probably reduce all-cause mortality; They...,They probably reduce all-cause mortality,Adults admitted to hospital at least once for ...,Adults admitted to hospital at least once for ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
127,1033,How do case management interventions compare w...,What were the primary motivations for explorin...,Select all of the following that are colors,How does the study describe the effect of mult...,Identify the populations studied in the trials...,Case management may reduce all-cause mortality...,Case management may reduce all-cause mortality.,To provide ongoing support rather than crisis ...,To provide ongoing support rather than crisis ...,blue; green; pink,blue; green; pink,They probably reduce all-cause mortality; They...,They probably reduce all-cause mortality,Adults admitted to hospital at least once for ...,Adults admitted to hospital at least once for ...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1107
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
96,1107,"In evaluating the study outcomes, how should t...",Which methodological approaches from this revi...,Select all of the following that are fruits,"Based on the plain-language summary, how could...",Which outcome did the research hope to clarify...,Inconsistent results suggest caution in widesp...,Inconsistent results suggest caution in widesp...,Only include studies with the most positive ou...,Increase uniformity in disease severity among ...,dog; blue; grape,grape,By increasing the number of studies focusing o...,By increasing the number of studies focusing o...,Need for mechanical ventilation; Cure for COVI...,Need for mechanical ventilation

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
136,1107,"In evaluating the study outcomes, how should t...",Which methodological approaches from this revi...,Select all of the following that are fruits,"Based on the plain-language summary, how could...",Which outcome did the research hope to clarify...,Inconsistent results suggest caution in widesp...,Inconsistent results suggest caution in widesp...,Only include studies with the most positive ou...,Increase uniformity in disease severity among ...,dog; blue; grape,grape,By increasing the number of studies focusing o...,By increasing the number of studies focusing o...,Need for mechanical ventilation; Cure for COVI...,Need for mechanical ventilation

==============================
ABSTRACT ID: 1025
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
21,1025,How do observational studies and randomised tr...,Critically judge the hypothesis that increasin...,Select all of the following that are colors,What was the primary aim of the reviewed study?,What inference about selenium supplementation ...,Observational studies suggest an inverse relat...,Observational studies suggest an inverse relat...,The hypothesis is supported by high-quality ra...,The hypothesis is not supported by epidemiolog...,blue; green; pink,blue; green; pink,To determine the nutritional benefits of selen...,To investigate the relationship between seleni...,Selenium supplementation might increase the ri...,Selenium supplementation might increase the ri...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
137,1025,How do observational studies and randomised tr...,Critically judge the hypothesis that increasin...,Select all of the following that are colors,What was the primary aim of the reviewed study?,What inference about selenium supplementation ...,Observational studies suggest an inverse relat...,Observational studies suggest an inverse relat...,The hypothesis is supported by high-quality ra...,The hypothesis is not supported by epidemiolog...,blue; green; pink,blue; green; pink,To determine the nutritional benefits of selen...,To investigate the relationship between seleni...,Selenium supplementation might increase the ri...,Selenium supplementation might increase the ri...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1116
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
103,1116,What might be the implications of the study's ...,What is the primary focus of the study?,Select all of the following that are fruits,Which treatments were compared in the study?,How are long-term treatments intended to benef...,Continued antidepressant medication offers a d...,Psychotherapy could potentially be more effect...,Assessing continuation and maintenance treatme...,Assessing continuation and maintenance treatme...,dog; blue; grape,grape,Antidepressant medications versus placebo; Psy...,Antidepressant medications versus placebo; Psy...,Preventing recurrence of depressive symptoms; ...,Preventing recurrence of depressive symptoms

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
146,1116,What might be the implications of the study's ...,What is the primary focus of the study?,Select all of the following that are fruits,Which treatments were compared in the study?,How are long-term treatments intended to benef...,Continued antidepressant medication offers a d...,Psychotherapy could potentially be more effect...,Assessing continuation and maintenance treatme...,Assessing continuation and maintenance treatme...,dog; blue; grape,grape,Antidepressant medications versus placebo; Psy...,Antidepressant medications versus placebo; Psy...,Preventing recurrence of depressive symptoms; ...,Preventing recurrence of depressive symptoms

==============================
ABSTRACT ID: 1062
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
54,1062,How did the variation in treatment delivery ac...,What is one main focus of organised care servi...,Select all of the following that are fruits,Compare the impact of organised care services ...,NaN,It reduced confidence due to inconsistent meth...,It reduced confidence due to inconsistent meth...,Improving people's care experiences; Increasin...,Improving people's care experiences,dog; blue; grape,grape,Organised care services prevent more heart-rel...,Organised care services prevent more heart-rel...,NaN,NaN

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
154,1062,How did the variation in treatment delivery ac...,What is one main focus of organised care servi...,Select all of the following that are fruits,Compare the impact of organised care services ...,NaN,It reduced confidence due to inconsistent meth...,It reduced confidence due to inconsistent meth...,Improving people's care experiences; Increasin...,Improving people's care experiences,dog; blue; grape,grape,Organised care services prevent more heart-rel...,Organised care services prevent more heart-rel...,NaN,NaN

==============================
ABSTRACT ID: 1125
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
110,1125,What conclusions can be drawn about the influe...,How might the engagement of care partners in C...,Select the items that are animals,What are the implications of CR's effects on t...,How is the success of cognitive rehabilitation...,CR significantly boosts confidence immediately...,CR significantly boosts confidence immediately...,Involving care partners might enhance the perc...,Involving care partners might enhance the perc...,Chair; Lamp; Dog,Dog,CR likely improves the psychological wellbeing...,CR likely improves the psychological wellbeing...,By the increase in brain size; By improvement ...,By improvement in chosen tasks or activities

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
155,1125,What conclusions can be drawn about the influe...,How might the engagement of care partners in C...,Select the items that are animals,What are the implications of CR's effects on t...,How is the success of cognitive rehabilitation...,CR significantly boosts confidence immediately...,CR significantly boosts confidence immediately...,Involving care partners might enhance the perc...,Involving care partners might enhance the perc...,Chair; Lamp; Dog,Dog,CR likely improves the psychological wellbeing...,CR likely improves the psychological wellbeing...,By the increase in brain size; By improvement ...,By improvement in chosen tasks or activities

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1055
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
47,1055,What types of injuries are hyperextension inju...,What was the motivation behind the review?,Select all of the following that are colors,Which methods of conservative treatment were c...,Summarize the results reported regarding diffe...,Ligament injuries from finger hyperextension; ...,Ligament injuries from finger hyperextension,To find the best non-surgical treatment for fi...,To find the best non-surgical treatment for fi...,blue; green; pink,blue; green; pink,Unrestricted mobility vs. immobilisation; Only...,Unrestricted mobility vs. immobilisation,No important differences found; Significant ou...,No important differences found; Minor differen...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
163,1055,What types of injuries are hyperextension inju...,What was the motivation behind the review?,Select all of the following that are colors,Which methods of conservative treatment were c...,Summarize the results reported regarding diffe...,Ligament injuries from finger hyperextension; ...,Ligament injuries from finger hyperextension,To find the best non-surgical treatment for fi...,To find the best non-surgical treatment for fi...,blue; green; pink,blue; green; pink,Unrestricted mobility vs. immobilisation; Only...,Unrestricted mobility vs. immobilisation,No important differences found; Significant ou...,No important differences found; Minor differen...

==============================
ABSTRACT ID: 1021
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
17,1021,What can be deduced about the role of thymic p...,What factors are likely leading researchers to...,Select all of the following that are colors,Evaluate the potential impact of thymosin ?1 a...,What was the purpose of the review involving t...,Thymic peptides completely prevent adverse eff...,There is evidence to suggest thymic peptides m...,A lack of conclusive evidence supporting their...,A lack of conclusive evidence supporting their...,blue; green; pink,blue; green; pink,Thymosin ?1 has shown definitive improvement i...,"The trend suggests a potential benefit, but re...",To determine if they improve chemotherapy resp...,To determine if they improve chemotherapy resp...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
164,1021,What can be deduced about the role of thymic p...,What factors are likely leading researchers to...,Select all of the following that are colors,Evaluate the potential impact of thymosin ?1 a...,What was the purpose of the review involving t...,Thymic peptides completely prevent adverse eff...,There is evidence to suggest thymic peptides m...,A lack of conclusive evidence supporting their...,A lack of conclusive evidence supporting their...,blue; green; pink,blue; green; pink,Thymosin ?1 has shown definitive improvement i...,"The trend suggests a potential benefit, but re...",To determine if they improve chemotherapy resp...,To determine if they improve chemotherapy resp...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1129
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
114,1129,What conclusions can be drawn from the study r...,How does the evidence from the review support ...,Select the items that are animals,What factors would need to be addressed in fut...,What was the primary focus of the study?,B vitamins significantly improve overall cogni...,B vitamins have little or no effect on overall...,Vitamin E has no significant effect on the pro...,Vitamin E has no significant effect on the pro...,Chair; Lamp; Dog,Dog,Increased sample sizes and long-term studies.;...,Increased sample sizes and long-term studies.,Reducing the risk of developing dementia with ...,Reducing the risk of developing dementia with ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
172,1129,What conclusions can be drawn from the study r...,How does the evidence from the review support ...,Select the items that are animals,What factors would need to be addressed in fut...,What was the primary focus of the study?,B vitamins significantly improve overall cogni...,B vitamins have little or no effect on overall...,Vitamin E has no significant effect on the pro...,Vitamin E has no significant effect on the pro...,Chair; Lamp; Dog,Dog,Increased sample sizes and long-term studies.;...,Increased sample sizes and long-term studies.,Reducing the risk of developing dementia with ...,Reducing the risk of developing dementia with ...
461,1129,What conclusions can be drawn from the study r...,How does the evidence from the review support ...,Select the items that are articles of clothing,What factors would need to be addressed in fut...,What was the primary focus of the study?,B vitamins significantly improve overall cogni...,B vitamins have little or no effect on overall...,Vitamin E has no significant effect on the pro...,Vitamin E has no significant effect on the pro...,shirt; jeans; jacket,shirt; jeans; jacket,Increased sample sizes and long-term studies.;...,Increased sample sizes and long-term studies.,Reducing the risk of developing dementia with ...,Reducing the risk of developing dementia with ...

==============================
ABSTRACT ID: 1098
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
87,1098,What factors may influence the effectiveness o...,How do organisational interventions compare to...,Select the items that are animals,"In assessing the interventions, what might be ...",Which group showed a weight reduction from edu...,The use of clinical decision support tools; Th...,The use of clinical decision support tools; Ta...,Organisational interventions may lead to great...,Organisational interventions may lead to great...,Chair; Lamp; Dog,Dog,Variability in participant demographics; The l...,The low certainty of evidence,Adult patients; Children with obesity; Healthc...,Adult patients

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
173,1098,What factors may influence the effectiveness o...,How do organisational interventions compare to...,Select the items that are articles of clothing,"In assessing the interventions, what might be ...",Which group showed a weight reduction from edu...,The use of clinical decision support tools; Th...,The use of clinical decision support tools; Ta...,Organisational interventions may lead to great...,Organisational interventions may lead to great...,shirt; jeans; jacket,shirt; jeans; jacket,Variability in participant demographics; The l...,The low certainty of evidence,Adult patients; Children with obesity; Healthc...,Adult patients
415,1098,What factors may influence the effectiveness o...,How do organisational interventions compare to...,Select the items that are animals,"In assessing the interventions, what might be ...",Which group showed a weight reduction from edu...,The use of clinical decision support tools; Th...,The use of clinical decision support tools; Ta...,Organisational interventions may lead to great...,Organisational interventions may lead to great...,Chair; Lamp; Dog,Dog,Variability in participant demographics; The l...,The low certainty of evidence,Adult patients; Children with obesity; Healthc...,Adult patients

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1026
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
22,1026,How can the impact of dietary interventions on...,What was the primary motivation for undertakin...,Select all of the following that are colors,What does the evidence suggest about dietary i...,What is one reported outcome of dietary interv...,Dietary interventions slightly improved the Di...,Dietary interventions slightly improved the Di...,To evaluate evidence on dietary advice for peo...,To evaluate evidence on dietary advice for peo...,blue; green; pink,blue; green; pink,Dietary interventions probably lead to a sligh...,Dietary interventions probably lead to a sligh...,Improvement compared to control; Decrease comp...,Improvement compared to control

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
181,1026,How can the impact of dietary interventions on...,What was the primary motivation for undertakin...,Select all of the following that are colors,What does the evidence suggest about dietary i...,What is one reported outcome of dietary interv...,Dietary interventions slightly improved the Di...,Dietary interventions slightly improved the Di...,To evaluate evidence on dietary advice for peo...,To evaluate evidence on dietary advice for peo...,blue; green; pink,blue; green; pink,Dietary interventions probably lead to a sligh...,Dietary interventions probably lead to a sligh...,Improvement compared to control; Decrease comp...,Improvement compared to control

==============================
ABSTRACT ID: 1117
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
104,1117,In assessing the study's outcomes for psycholo...,What conclusions can be made about the role of...,Select all of the following that are colors,What was one of the main motivations for condu...,What types of treatments did the study focus on?,Effectiveness across different ethnic populati...,Effectiveness across different ethnic populati...,It is not effective in reducing depressive sym...,It is not effective in reducing depressive sym...,blue; green; pink,blue; green; pink,Depression is often detected after a stroke.; ...,Depression is an important morbidity associate...,"Pharmacological treatments, non-invasive brain...","Pharmacological treatments, non-invasive brain..."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
182,1117,In assessing the study's outcomes for psycholo...,What conclusions can be made about the role of...,Select the items that are animals,What was one of the main motivations for condu...,What types of treatments did the study focus on?,Effectiveness across different ethnic populati...,Effectiveness across different ethnic populati...,It is not effective in reducing depressive sym...,It is not effective in reducing depressive sym...,Chair; Lamp; Dog,Dog,Depression is often detected after a stroke.; ...,Depression is an important morbidity associate...,"Pharmacological treatments, non-invasive brain...","Pharmacological treatments, non-invasive brain..."
344,1117,In assessing the study's outcomes for psycholo...,What conclusions can be made about the role of...,Select all of the following that are colors,What was one of the main motivations for condu...,What types of treatments did the study focus on?,Effectiveness across different ethnic populati...,Effectiveness across different ethnic populati...,It is not effective in reducing depressive sym...,It is not effective in reducing depressive sym...,blue; green; pink,blue; green; pink,Depression is often detected after a stroke.; ...,Depression is an important morbidity associate...,"Pharmacological treatments, non-invasive brain...","Pharmacological treatments, non-invasive brain..."

==============================
ABSTRACT ID: 1097
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
86,1097,What can be inferred about the role of clinici...,"Based on the review, hypothesize a new combina...",Select all of the following that are colors,Which quality improvement strategy combination...,Which strategies were identified as most effec...,They are essential when combined with team cha...,They are essential when combined with team cha...,"Patient education, financial incentives, and c...","Patient education, financial incentives, and c...",blue; green; pink,blue; green; pink,"Patient education, patient reminders, and clin...","Case management, patient education, and electr...",Case management and clinician education; Patie...,Patient education and team changes

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
190,1097,What can be inferred about the role of clinici...,"Based on the review, hypothesize a new combina...",Select all of the following that are colors,Which quality improvement strategy combination...,Which strategies were identified as most effec...,They are essential when combined with team cha...,They are essential when combined with team cha...,"Patient education, financial incentives, and c...","Patient education, financial incentives, and c...",blue; green; pink,blue; green; pink,"Patient education, patient reminders, and clin...","Case management, patient education, and electr...",Case management and clinician education; Patie...,Patient education and team changes

==============================
ABSTRACT ID: 1009
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
7,1009,What conclusions can be drawn about the certai...,What was the main motivation for the study on ...,Select the items that are animals,Which antidiabetic medication combination was ...,What are some important outcomes assessed in t...,The evidence is generally low-certainty due to...,The evidence is generally low-certainty due to...,To determine side effects of metformin plus su...,To investigate effects compared with other ant...,Chair; Lamp; Dog,Dog,Metformin plus insulin; Metformin plus sulphon...,Metformin plus sulphonylurea,Health-related quality of life; Increase in mu...,Health-related quality of life; Complications ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
191,1009,What conclusions can be drawn about the certai...,What was the main motivation for the study on ...,Select the items that are animals,Which antidiabetic medication combination was ...,What are some important outcomes assessed in t...,The evidence is generally low-certainty due to...,The evidence is generally low-certainty due to...,To determine side effects of metformin plus su...,To investigate effects compared with other ant...,Chair; Lamp; Dog,Dog,Metformin plus insulin; Metformin plus sulphon...,Metformin plus sulphonylurea,Health-related quality of life; Increase in mu...,Health-related quality of life; Complications ...

==============================
ABSTRACT ID: 1084
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
75,1084,What condition involves kidneys leaking protei...,Identify a type of medication used to manage b...,Select all of the following that are colors,Summarize the main reason for using lipid-lowe...,Describe the evidence available for the effect...,Nephrotic syndrome; Hypertension; Diabetes,Nephrotic syndrome,Statins; Antibiotics; Painkillers,Statins,blue; green; pink,blue; green; pink,To reduce blood fat levels; To increase urinat...,To reduce blood fat levels,Insufficient high-quality research; Clear and ...,Insufficient high-quality research

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
199,1084,What condition involves kidneys leaking protei...,Identify a type of medication used to manage b...,Select all of the following that are colors,Summarize the main reason for using lipid-lowe...,Describe the evidence available for the effect...,Nephrotic syndrome; Hypertension; Diabetes,Nephrotic syndrome,Statins; Antibiotics; Painkillers,Statins,blue; green; pink,blue; green; pink,To reduce blood fat levels; To increase urinat...,To reduce blood fat levels,Insufficient high-quality research; Clear and ...,Insufficient high-quality research
820,1084,What condition involves kidneys leaking protei...,Identify a type of medication used to manage b...,Select all of the following that are fruits,Summarize the main reason for using lipid-lowe...,Describe the evidence available for the effect...,Nephrotic syndrome; Hypertension; Diabetes,Nephrotic syndrome,Statins; Antibiotics; Painkillers,Statins,dog; blue; grape,grape,To reduce blood fat levels; To increase urinat...,To reduce blood fat levels,Insufficient high-quality research; Clear and ...,Insufficient high-quality research

==============================
ABSTRACT ID: 1048
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
42,1048,How do the reported side effects of fixed-dose...,Which methodological limitations could affect ...,Select the items that are animals,"According to the findings, how did fixed-dose ...",What effect did the fixed-dose combination pil...,They are more frequent in the fixed-dose combi...,They are more frequent in the fixed-dose combi...,The inability to blind participants and resear...,The inability to blind participants and resear...,Chair; Lamp; Dog,Dog,It significantly improved adherence by simplif...,It significantly improved adherence by simplif...,It reduced systolic blood pressure by about 6 ...,It reduced systolic blood pressure by about 6 ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
200,1048,How do the reported side effects of fixed-dose...,Which methodological limitations could affect ...,Select the items that are animals,"According to the findings, how did fixed-dose ...",What effect did the fixed-dose combination pil...,They are more frequent in the fixed-dose combi...,They are more frequent in the fixed-dose combi...,The inability to blind participants and resear...,The inability to blind participants and resear...,Chair; Lamp; Dog,Dog,It significantly improved adherence by simplif...,It significantly improved adherence by simplif...,It reduced systolic blood pressure by about 6 ...,It reduced systolic blood pressure by about 6 ...

==============================
ABSTRACT ID: 1022
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
18,1022,In what ways do the reviewed treatments reflec...,What was the main purpose of the study?,Select all of the following that are colors,Which treatment appeared most effective for fi...,Describe how combination therapies for GBM fir...,Lack of treatments with clear survival benefit...,Lack of treatments with clear survival benefits,To establish a new treatment protocol for GBM....,To evaluate treatments for GBM recurrence.,blue; green; pink,blue; green; pink,Bevacizumab plus lomustine.; Lomustine alone.;...,Lomustine alone.,Combination therapies improved overall surviva...,Combination therapies often increased severe a...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
209,1022,In what ways do the reviewed treatments reflec...,What was the main purpose of the study?,Select all of the following that are colors,Which treatment appeared most effective for fi...,Describe how combination therapies for GBM fir...,Lack of treatments with clear survival benefit...,Lack of treatments with clear survival benefits,To establish a new treatment protocol for GBM....,To evaluate treatments for GBM recurrence.,blue; green; pink,blue; green; pink,Bevacizumab plus lomustine.; Lomustine alone.;...,Lomustine alone.,Combination therapies improved overall surviva...,Combination therapies often increased severe a...
748,1022,In what ways do the reviewed treatments reflec...,What was the main purpose of the study?,Select the items that are articles of clothing,Which treatment appeared most effective for fi...,Describe how combination therapies for GBM fir...,Lack of treatments with clear survival benefit...,Lack of treatments with clear survival benefits,To establish a new treatment protocol for GBM....,To evaluate treatments for GBM recurrence.,shirt; jeans; jacket,shirt; jeans; jacket,Bevacizumab plus lomustine.; Lomustine alone.;...,Lomustine alone.,Combination therapies improved overall surviva...,Combination therapies often increased severe a...
965,1022,In what ways do the reviewed treatments reflec...,What was the main purpose of the study?,Select the items that are animals,Which treatment appeared most effective for fi...,Describe how combination therapies for GBM fir...,Lack of treatments with clear survival benefit...,Lack of treatments with clear survival benefits,To establish a new treatment protocol for GBM....,To evaluate treatments for GBM recurrence.,Chair; Lamp; Dog,Dog,Bevacizumab plus lomustine.; Lomustine alone.;...,Lomustine alone.,Combination therapies improved overall surviva...,Combination therapies often increased severe a...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1030
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
26,1030,What reasoning might explain the moderate cert...,"Considering the study's findings, what might b...",Select all of the following that are colors,What bacterium is associated with an increased...,"In the context of the study, describe the repo...",The trials had varying levels of bias affectin...,The trials had varying levels of bias affectin...,Gastric cancer mortality can be significantly ...,Gastric cancer mortality can be significantly ...,blue; green; pink,blue; green; pink,Helicobacter pylori; Escherichia coli; Staphyl...,Helicobacter pylori,Decreases the incidence of gastric cancer; Inc...,Decreases the incidence of gastric cancer

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
217,1030,What reasoning might explain the moderate cert...,"Considering the study's findings, what might b...",Select all of the following that are colors,What bacterium is associated with an increased...,"In the context of the study, describe the repo...",The trials had varying levels of bias affectin...,The trials had varying levels of bias affectin...,Gastric cancer mortality can be significantly ...,Gastric cancer mortality can be significantly ...,blue; green; pink,blue; green; pink,Helicobacter pylori; Escherichia coli; Staphyl...,Helicobacter pylori,Decreases the incidence of gastric cancer; Inc...,Decreases the incidence of gastric cancer

==============================
ABSTRACT ID: 1110
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
99,1110,What are the implications of the short follow-...,How could future research be designed to impro...,Select the items that are animals,What reasoning supports the conclusion that mo...,How did the results of CoronaVac differ betwee...,Long-term effectiveness might be underestimate...,Long-term effectiveness might be underestimate...,Incorporating diverse geographic regions where...,Incorporating diverse geographic regions where...,Chair; Lamp; Dog,Dog,High-certainty evidence from multiple trials d...,High-certainty evidence from multiple trials d...,The trials demonstrated contradictory efficacy...,The trials demonstrated contradictory efficacy...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
218,1110,What are the implications of the short follow-...,How could future research be designed to impro...,Select the items that are animals,What reasoning supports the conclusion that mo...,How did the results of CoronaVac differ betwee...,Long-term effectiveness might be underestimate...,Long-term effectiveness might be underestimate...,Incorporating diverse geographic regions where...,Incorporating diverse geographic regions where...,Chair; Lamp; Dog,Dog,High-certainty evidence from multiple trials d...,High-certainty evidence from multiple trials d...,The trials demonstrated contradictory efficacy...,The trials demonstrated contradictory efficacy...

==============================

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

ABSTRACT ID: 1029
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
25,1029,What distinctions are made in the study regard...,How would you evaluate the implications of vit...,Select all of the following that are colors,Identify the demographic group where vitamin C...,Explain the overall finding of the study regar...,Vitamin A increases lung cancer risk in smoker...,Vitamin A increases lung cancer risk in smoker...,The study shows vitamin E poses a high risk fo...,The study shows vitamin E poses a high risk fo...,blue; green; pink,blue; green; pink,Men; Women; Children,Women,Vitamins prevent lung cancer; Vitamins have no...,Vitamins have no effect on preventing lung can...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
226,1029,What distinctions are made in the study regard...,How would you evaluate the implications of vit...,Select all of the following that are colors,Identify the demographic group where vitamin C...,Explain the overall finding of the study regar...,Vitamin A increases lung cancer risk in smoker...,Vitamin A increases lung cancer risk in smoker...,The study shows vitamin E poses a high risk fo...,The study shows vitamin E poses a high risk fo...,blue; green; pink,blue; green; pink,Men; Women; Children,Women,Vitamins prevent lung cancer; Vitamins have no...,Vitamins have no effect on preventing lung can...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1091
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
82,1091,What is one potential benefit of antiplatelet ...,Which outcome is not significantly reduced by ...,Select all of the following that are colors,Identify a potential risk associated with anti...,Describe the impact of antiplatelet agents on ...,Preventing heart attacks; Reducing all-cause m...,Preventing heart attacks,Stroke; Heart attack; Dialysis access clotting,Stroke,blue; green; pink,blue; green; pink,Major bleeding; Increased kidney function; Dec...,Major bleeding,They probably prevent heart attacks.; They hav...,They probably prevent heart attacks.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
227,1091,What is one potential benefit of antiplatelet ...,Which outcome is not significantly reduced by ...,Select the items that are articles of clothing,Identify a potential risk associated with anti...,Describe the impact of antiplatelet agents on ...,Preventing heart attacks; Reducing all-cause m...,Preventing heart attacks,Stroke; Heart attack; Dialysis access clotting,Stroke,shirt; jeans; jacket,shirt; jeans; jacket,Major bleeding; Increased kidney function; Dec...,Major bleeding,They probably prevent heart attacks.; They hav...,They probably prevent heart attacks.
523,1091,What is one potential benefit of antiplatelet ...,Which outcome is not significantly reduced by ...,Select all of the following that are colors,Identify a potential risk associated with anti...,Describe the impact of antiplatelet agents on ...,Preventing heart attacks; Reducing all-cause m...,Preventing heart attacks,Stroke; Heart attack; Dialysis access clotting,Stroke,blue; green; pink,blue; green; pink,Major bleeding; Increased kidney function; Dec...,Major bleeding,They probably prevent heart attacks.; They hav...,They probably prevent heart attacks.

==============================
ABSTRACT ID: 1054
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
46,1054,What are the motivations behind examining the ...,What types of injuries are classified as open ...,Select all of the following that are fruits,Explain why immediate antibiotic administratio...,Summarize the uncertainty in outcomes related ...,To optimize treatment outcomes by reducing inf...,To optimize treatment outcomes by reducing inf...,Injuries with open skin wounds around the brea...,Injuries with open skin wounds around the break,dog; blue; grape,grape,To reduce the risk of deep infection; To promo...,To reduce the risk of deep infection,Unclear impact on infection rates and delayed ...,Unclear impact on infection rates and delayed ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
235,1054,What are the motivations behind examining the ...,What types of injuries are classified as open ...,Select all of the following that are colors,Explain why immediate antibiotic administratio...,Summarize the uncertainty in outcomes related ...,To optimize treatment outcomes by reducing inf...,To optimize treatment outcomes by reducing inf...,Injuries with open skin wounds around the brea...,Injuries with open skin wounds around the break,blue; green; pink,blue; green; pink,To reduce the risk of deep infection; To promo...,To reduce the risk of deep infection,Unclear impact on infection rates and delayed ...,Unclear impact on infection rates and delayed ...
263,1054,What are the motivations behind examining the ...,What types of injuries are classified as open ...,Select all of the following that are fruits,Explain why immediate antibiotic administratio...,Summarize the uncertainty in outcomes related ...,To optimize treatment outcomes by reducing inf...,To optimize treatment outcomes by reducing inf...,Injuries with open skin wounds around the brea...,Injuries with open skin wounds around the break,dog; blue; grape,grape,To reduce the risk of deep infection; To promo...,To reduce the risk of deep infection,Unclear impact on infection rates and delayed ...,Unclear impact on infection rates and delayed ...
866,1054,What are the motivations behind examining the ...,What types of injuries are classified as open ...,Select the items that are animals,Explain why immediate antibiotic administratio...,Summarize the uncertainty in outcomes related ...,To optimize treatment outcomes by reducing inf...,To optimize treatment outcomes by reducing inf...,Injuries with open skin wounds around the brea...,Injuries with open skin wounds around the break,Chair; Lamp; Dog,Dog,To reduce the risk of deep infection; To promo...,To reduce the risk of deep infection,Unclear impact on infection rates and delayed ...,Unclear impact on infection rates and delayed ...

==============================
ABSTRACT ID: 1070
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
62,1070,How should the results be evaluated in terms o...,What was the main goal of the study regarding ...,Select all of the following that are fruits,What did the study use blood pressure-lowering...,How is the evidence quality of the trials desc...,The results are pivotal as they highlight pote...,The results are pivotal as they highlight pote...,To determine if they prevent recurrent stroke ...,To determine if they prevent recurrent stroke ...,dog; blue; grape,grape,To lower the risk of recurrent stroke; To incr...,To lower the risk of recurrent stroke,Moderate; High; Low,Moderate

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
236,1070,How should the results be evaluated in terms o...,What was the main goal of the study regarding ...,Select all of the following that are fruits,What did the study use blood pressure-lowering...,How is the evidence quality of the trials desc...,The results are pivotal as they highlight pote...,The results are pivotal as they highlight pote...,To determine if they prevent recurrent stroke ...,To determine if they prevent recurrent stroke ...,dog; blue; grape,grape,To lower the risk of recurrent stroke; To incr...,To lower the risk of recurrent stroke,Moderate; High; Low,Moderate

==============================
ABSTRACT ID: 1103
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
92,1103,Evaluate the impact of sugar taxation on publi...,What potential effects on food reformulation m...,Select all of the following that are fruits,Analyze the reasons for including various coun...,Judge the reliability of the study based on th...,It may motivate policy changes to implement su...,It may motivate policy changes to implement su...,Industries could reduce added sugar in product...,Industries could reduce added sugar in products.,dog; blue; grape,grape,To provide a comprehensive review of internati...,To facilitate the exploration of diverse tax-r...,The methods used were robust and reliable.; Th...,The study lacked strong methods and classifica...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
245,1103,Evaluate the impact of sugar taxation on publi...,What potential effects on food reformulation m...,Select the items that are articles of clothing,Analyze the reasons for including various coun...,Judge the reliability of the study based on th...,It may motivate policy changes to implement su...,It may motivate policy changes to implement su...,Industries could reduce added sugar in product...,Industries could reduce added sugar in products.,shirt; jeans; jacket,shirt; jeans; jacket,To provide a comprehensive review of internati...,To facilitate the exploration of diverse tax-r...,The methods used were robust and reliable.; Th...,The study lacked strong methods and classifica...
317,1103,Evaluate the impact of sugar taxation on publi...,What potential effects on food reformulation m...,Select all of the following that are fruits,Analyze the reasons for including various coun...,Judge the reliability of the study based on th...,It may motivate policy changes to implement su...,It may motivate policy changes to implement su...,Industries could reduce added sugar in product...,Industries could reduce added sugar in products.,dog; blue; grape,grape,To provide a comprehensive review of internati...,To facilitate the exploration of diverse tax-r...,The methods used were robust and reliable.; Th...,The study lacked strong methods and classifica...

==============================
ABSTRACT ID: 1057
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
49,1057,What was the main aim of the Cochrane Review?,How is 'anophthalmia' defined in the review?,Select the items that are animals,Describe the role of blood vessels in integrat...,How do review authors view the certainty of th...,To determine if integrated orbital implants ar...,To determine if integrated orbital implants ar...,The presence of an extra eye in the orbit.; Th...,The absence of the eye in the orbit.,Chair; Lamp; Dog,Dog,Blood vessels grow into the implant material.;...,Blood vessels grow into the implant material.,They have high certainty about the evidence.; ...,They view the evidence as having very little c...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
253,1057,What was the main aim of the Cochrane Review?,How is 'anophthalmia' defined in the review?,Select the items that are articles of clothing,Describe the role of blood vessels in integrat...,How do review authors view the certainty of th...,To determine if integrated orbital implants ar...,To determine if integrated orbital implants ar...,The presence of an extra eye in the orbit.; Th...,The absence of the eye in the orbit.,shirt; jeans; jacket,shirt; jeans; jacket,Blood vessels grow into the implant material.;...,Blood vessels grow into the implant material.,They have high certainty about the evidence.; ...,They view the evidence as having very little c...

==============================
ABSTRACT ID: 1019
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
15,1019,In evaluating the effectiveness of bisphosphon...,What can be deduced about the impact of bispho...,Select the items that are animals,Which group showed improved survival with bisp...,Did bisphosphonates improve the quality of lif...,Bisphosphonates probably lowered the risk of c...,Bisphosphonates probably lowered the risk of c...,Bisphosphonates did not improve survival.; Bis...,Bisphosphonates did not improve survival.,Chair; Lamp; Dog,Dog,Postmenopausal women; Premenopausal women; Bot...,Postmenopausal women,"Yes, slightly better quality of life compared ...","Yes, slightly better quality of life compared ..."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
254,1019,In evaluating the effectiveness of bisphosphon...,What can be deduced about the impact of bispho...,Select the items that are animals,Which group showed improved survival with bisp...,Did bisphosphonates improve the quality of lif...,Bisphosphonates probably lowered the risk of c...,Bisphosphonates probably lowered the risk of c...,Bisphosphonates did not improve survival.; Bis...,Bisphosphonates did not improve survival.,Chair; Lamp; Dog,Dog,Postmenopausal women; Premenopausal women; Bot...,Postmenopausal women,"Yes, slightly better quality of life compared ...","Yes, slightly better quality of life compared ..."

==============================
ABSTRACT ID: 1094
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
83,1094,How might the study's conclusion about the eff...,Evaluate the potential impact of publication b...,Select the items that are animals,How might the trial design be improved to ensu...,What could be deduced about the weight of evid...,The conclusion may be overstated due to the ve...,The conclusion may be overstated due to the ve...,Publication bias may have led to an underestim...,Publication bias may have led to an underestim...,Chair; Lamp; Dog,Dog,Incorporate a larger number of double-blind tr...,Incorporate a larger number of double-blind tr...,There might be an increased likelihood of posi...,There might be an increased likelihood of posi...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
262,1094,How might the study's conclusion about the eff...,Evaluate the potential impact of publication b...,Select the items that are animals,How might the trial design be improved to ensu...,What could be deduced about the weight of evid...,The conclusion may be overstated due to the ve...,The conclusion may be overstated due to the ve...,Publication bias may have led to an underestim...,Publication bias may have led to an underestim...,Chair; Lamp; Dog,Dog,Incorporate a larger number of double-blind tr...,Incorporate a larger number of double-blind tr...,There might be an increased likelihood of posi...,There might be an increased likelihood of posi...

==============================
ABSTRACT ID: 1118
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
105,1118,How does the presence of depression influence ...,What criteria should future studies meet to im...,Select all of the following that are colors,What is the main conclusion about antidepressa...,"In the summary, how did adverse events affect ...",It enhances the retention of participants in t...,It negatively impacts the treatment outcomes.,Larger randomized trials with relevant outcome...,Larger randomized trials with relevant outcome...,blue; green; pink,blue; green; pink,Little evidence supports their use; They are h...,Little evidence supports their use,They led to more study withdrawals; They had n...,They led to more study withdrawals

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
280,1118,How does the presence of depression influence ...,What criteria should future studies meet to im...,Select the items that are articles of clothing,What is the main conclusion about antidepressa...,"In the summary, how did adverse events affect ...",It enhances the retention of participants in t...,It negatively impacts the treatment outcomes.,Larger randomized trials with relevant outcome...,Larger randomized trials with relevant outcome...,shirt; jeans; jacket,shirt; jeans; jacket,Little evidence supports their use; They are h...,Little evidence supports their use,They led to more study withdrawals; They had n...,They led to more study withdrawals
758,1118,How does the presence of depression influence ...,What criteria should future studies meet to im...,Select all of the following that are colors,What is the main conclusion about antidepressa...,"In the summary, how did adverse events affect ...",It enhances the retention of participants in t...,It negatively impacts the treatment outcomes.,Larger randomized trials with relevant outcome...,Larger randomized trials with relevant outcome...,blue; green; pink,blue; green; pink,Little evidence supports their use; They are h...,Little evidence supports their use,They led to more study withdrawals; They had n...,They led to more study withdrawals

==============================
ABSTRACT ID: 1100
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
89,1100,What are the critical factors to consider when...,What aspects would be important to evaluate wh...,Select all of the following that are colors,How might the lack of consistent definitions f...,What strategies could be devised to enhance th...,The average weight loss in both diet groups ov...,The average weight loss in both diet groups ov...,The duration of each trial conducted; The vari...,The duration of each trial conducted,blue; green; pink,blue; green; pink,It introduces variability that could impact th...,It introduces variability that could impact th...,Implementing consistent definitions across tri...,Implementing consistent definitions across tri...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
281,1100,What are the critical factors to consider when...,What aspects would be important to evaluate wh...,Select all of the following that are colors,How might the lack of consistent definitions f...,What strategies could be devised to enhance th...,The average weight loss in both diet groups ov...,The average weight loss in both diet groups ov...,The duration of each trial conducted; The vari...,The duration of each trial conducted,blue; green; pink,blue; green; pink,It introduces variability that could impact th...,It introduces variability that could impact th...,Implementing consistent definitions across tri...,Implementing consistent definitions across tri...

==============================
ABSTRACT ID: 1071
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
63,1071,What is the primary purpose of aspirin in pati...,Which of the following describes the main comp...,Select all of the following that are colors,"According to the summary, what were the two ma...",Which thienopyridine is recommended as an alte...,To prevent blood clots from forming; To cure s...,To prevent blood clots from forming,Comparing thienopyridines with aspirin; Compar...,Comparing thienopyridines with aspirin,blue; green; pink,blue; green; pink,Diarrhoea and skin rash; Heart attack and stro...,Diarrhoea and skin rash,Clopidogrel; Ticlopidine; Aspirin,Clopidogrel

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
290,1071,What is the primary purpose of aspirin in pati...,Which of the following describes the main comp...,Select all of the following that are colors,"According to the summary, what were the two ma...",Which thienopyridine is recommended as an alte...,To prevent blood clots from forming; To cure s...,To prevent blood clots from forming,Comparing thienopyridines with aspirin; Compar...,Comparing thienopyridines with aspirin,blue; green; pink,blue; green; pink,Diarrhoea and skin rash; Heart attack and stro...,Diarrhoea and skin rash,Clopidogrel; Ticlopidine; Aspirin,Clopidogrel

==============================
ABSTRACT ID: 1040
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
34,1040,In evaluating the effectiveness of treatments ...,What is the primary focus of cardioversion tre...,Select the items that are animals,How are the effectiveness and safety of cardio...,Summarize the major finding for the treatment ...,Bepridil and quinidine may be effective in sel...,Bepridil and quinidine may be effective in sel...,Restoring normal heart rhythm; Increasing hear...,Restoring normal heart rhythm,Chair; Lamp; Dog,Dog,By comparing electrical shock and drugs to pla...,By comparing electrical shock and drugs to pla...,Electrical cardioversion with biphasic energy ...,Electrical cardioversion with biphasic energy ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
299,1040,In evaluating the effectiveness of treatments ...,What is the primary focus of cardioversion tre...,Select the items that are animals,How are the effectiveness and safety of cardio...,Summarize the major finding for the treatment ...,Bepridil and quinidine may be effective in sel...,Bepridil and quinidine may be effective in sel...,Restoring normal heart rhythm; Increasing hear...,Restoring normal heart rhythm,Chair; Lamp; Dog,Dog,By comparing electrical shock and drugs to pla...,By comparing electrical shock and drugs to pla...,Electrical cardioversion with biphasic energy ...,Electrical cardioversion with biphasic energy ...

==============================
ABSTRACT ID: 1109
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
98,1109,How could the exclusion of certain trials from...,What are the implications of finding little or...,Select all of the following that are colors,"Considering the studyÃ¢ÂÂs findings, how mig...",What was the main objective of the study discu...,It increases confidence by ensuring higher-qua...,It increases confidence by ensuring higher-qua...,Ivermectin should not be used as a standard tr...,Ivermectin should not be used as a standard tr...,blue; green; pink,blue; green; pink,"Focus on larger-scale, high-quality, double-bl...","Focus on larger-scale, high-quality, double-bl...",To assess the efficacy and safety of ivermecti...,To assess the efficacy and safety of ivermecti...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
307,1109,How could the exclusion of certain trials from...,What are the implications of finding little or...,Select all of the following that are colors,"Considering the studyÃ¢ÂÂs findings, how mig...",What was the main objective of the study discu...,It increases confidence by ensuring higher-qua...,It increases confidence by ensuring higher-qua...,Ivermectin should not be used as a standard tr...,Ivermectin should not be used as a standard tr...,blue; green; pink,blue; green; pink,"Focus on larger-scale, high-quality, double-bl...","Focus on larger-scale, high-quality, double-bl...",To assess the efficacy and safety of ivermecti...,To assess the efficacy and safety of ivermecti...

==============================
ABSTRACT ID: 1130
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
115,1130,What discrepancies can be deduced between the ...,What potential limitations of the study could ...,Select all of the following that are fruits,What strategies could be planned to address th...,Explain the potential effects of Souvenaid on ...,Differences in treatment duration affect the e...,Differences in treatment duration affect the e...,The inability to combine data due to differenc...,The inability to combine data due to differenc...,dog; blue; grape,grape,Standardizing outcome measurement methods acro...,Standardizing outcome measurement methods acro...,There was a high likelihood of reducing dement...,People were probably no more or less likely to...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
325,1130,What discrepancies can be deduced between the ...,What potential limitations of the study could ...,Select all of the following that are fruits,What strategies could be planned to address th...,Explain the potential effects of Souvenaid on ...,Differences in treatment duration affect the e...,Differences in treatment duration affect the e...,The inability to combine data due to differenc...,The inability to combine data due to differenc...,dog; blue; grape,grape,Standardizing outcome measurement methods acro...,Standardizing outcome measurement methods acro...,There was a high likelihood of reducing dement...,People were probably no more or less likely to...

==============================
ABSTRACT ID: 1065
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
57,1065,What was the primary motivation for studying G...,Which adverse event was frequently associated ...,Select the items that are animals,What was the conclusion regarding GABA recepto...,What is a possible risk of using GABA receptor...,To investigate their use as traditional sedati...,To evaluate their potential brain protection b...,Drowsiness; Nausea; Headache,Drowsiness,Chair; Lamp; Dog,Dog,They are strongly recommended for use.; Modera...,Moderate-quality evidence did not support thei...,Stupor due to sedative effects.; Increased blo...,Stupor due to sedative effects.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
334,1065,What was the primary motivation for studying G...,Which adverse event was frequently associated ...,Select the items that are animals,What was the conclusion regarding GABA recepto...,What is a possible risk of using GABA receptor...,To investigate their use as traditional sedati...,To evaluate their potential brain protection b...,Drowsiness; Nausea; Headache,Drowsiness,Chair; Lamp; Dog,Dog,They are strongly recommended for use.; Modera...,Moderate-quality evidence did not support thei...,Stupor due to sedative effects.; Increased blo...,Stupor due to sedative effects.

==============================
ABSTRACT ID: 1028
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
24,1028,What analysis of the study results indicates t...,What are the compounds in green tea believed t...,Select all of the following that are fruits,"According to the summary, which of the followi...",What is the overall conclusion of the studies ...,The inconsistency of evidence from experimenta...,The inconsistency of evidence from experimenta...,Polyphenols; Carotenoids; Flavonoids,Polyphenols,dog; blue; grape,grape,Gastrointestinal disorders; Improved vision; R...,Gastrointestinal disorders; Raised blood pressure,The effect is inconsistent; Green tea consiste...,The effect is inconsistent

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
352,1028,What analysis of the study results indicates t...,What are the compounds in green tea believed t...,Select all of the following that are fruits,"According to the summary, which of the followi...",What is the overall conclusion of the studies ...,The inconsistency of evidence from experimenta...,The inconsistency of evidence from experimenta...,Polyphenols; Carotenoids; Flavonoids,Polyphenols,dog; blue; grape,grape,Gastrointestinal disorders; Improved vision; R...,Gastrointestinal disorders; Raised blood pressure,The effect is inconsistent; Green tea consiste...,The effect is inconsistent
974,1028,What analysis of the study results indicates t...,What are the compounds in green tea believed t...,Select the items that are animals,"According to the summary, which of the followi...",What is the overall conclusion of the studies ...,The inconsistency of evidence from experimenta...,The inconsistency of evidence from experimenta...,Polyphenols; Carotenoids; Flavonoids,Polyphenols,Chair; Lamp; Dog,Dog,Gastrointestinal disorders; Improved vision; R...,Gastrointestinal disorders; Raised blood pressure,The effect is inconsistent; Green tea consiste...,The effect is inconsistent

==============================
ABSTRACT ID: 1015
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
12,1015,How does the study differentiate the impact of...,What critical gaps in the research were identi...,Select all of the following that are fruits,What is cancer-related fatigue?,"According to the summary, what effect does car...",By comparing cardiovascular training outcomes ...,By comparing cardiovascular training outcomes ...,Lack of studies on training before anticancer ...,Lack of studies on training before anticancer ...,dog; blue; grape,grape,An extreme feeling of tiredness over a long pe...,An extreme feeling of tiredness over a long pe...,It results in little to no difference.; It sig...,It results in little to no difference.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
353,1015,How does the study differentiate the impact of...,What critical gaps in the research were identi...,Select the items that are articles of clothing,What is cancer-related fatigue?,"According to the summary, what effect does car...",By comparing cardiovascular training outcomes ...,By comparing cardiovascular training outcomes ...,Lack of studies on training before anticancer ...,Lack of studies on training before anticancer ...,shirt; jeans; jacket,shirt; jeans; jacket,An extreme feeling of tiredness over a long pe...,An extreme feeling of tiredness over a long pe...,It results in little to no difference.; It sig...,It results in little to no difference.

==============================
ABSTRACT ID: 1108
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
97,1108,What inference can be drawn about the impact o...,What is the estimated effectiveness of convale...,Select all of the following that are colors,What conclusion can be drawn about the unwante...,What hypothesis could be formulated for furthe...,Convalescent plasma significantly reduces mort...,Convalescent plasma has no impact on mortality...,The plasma significantly improves quality of l...,There is little to no difference in quality of...,blue; green; pink,blue; green; pink,Convalescent plasma likely increases serious u...,The therapy probably makes no difference in th...,Convalescent plasma significantly enhances sym...,Further large-scale studies will clarify its i...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
361,1108,What inference can be drawn about the impact o...,What is the estimated effectiveness of convale...,Select all of the following that are colors,What conclusion can be drawn about the unwante...,What hypothesis could be formulated for furthe...,Convalescent plasma significantly reduces mort...,Convalescent plasma has no impact on mortality...,The plasma significantly improves quality of l...,There is little to no difference in quality of...,blue; green; pink,blue; green; pink,Convalescent plasma likely increases serious u...,The therapy probably makes no difference in th...,Convalescent plasma significantly enhances sym...,Further large-scale studies will clarify its i...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1063
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
55,1063,What motivations for exploring telerehabilitat...,What were the main objectives of the telerehab...,Select all of the following that are colors,What were the findings regarding activities of...,"According to the summary, how did telerehabili...",To find a more convenient and less expensive w...,To find a more convenient and less expensive w...,To compare telerehabilitation with face-to-fac...,To compare telerehabilitation with face-to-fac...,blue; green; pink,blue; green; pink,Similar outcomes were found for both methods; ...,Similar outcomes were found for both methods,No significant changes in mood were reported; ...,No significant changes in mood were reported

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
362,1063,What motivations for exploring telerehabilitat...,What were the main objectives of the telerehab...,Select the items that are articles of clothing,What were the findings regarding activities of...,"According to the summary, how did telerehabili...",To find a more convenient and less expensive w...,To find a more convenient and less expensive w...,To compare telerehabilitation with face-to-fac...,To compare telerehabilitation with face-to-fac...,shirt; jeans; jacket,shirt; jeans; jacket,Similar outcomes were found for both methods; ...,Similar outcomes were found for both methods,No significant changes in mood were reported; ...,No significant changes in mood were reported

==============================
ABSTRACT ID: 1076
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
68,1076,What is the primary health issue that macrolid...,Which bacterial infection is particularly prob...,Select all of the following that are colors,What is one known effect of macrolide antibiot...,"According to the study, what was a finding reg...",Infections in their airways; Heart disease; Di...,Infections in their airways,Pseudomonas aeruginosa; Escherichia coli; Stre...,Pseudomonas aeruginosa,blue; green; pink,blue; green; pink,Slight improvement at six months; Deterioratio...,Slight improvement at six months,The risk was lower compared to placebo; The ri...,The risk was lower compared to placebo

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
371,1076,What is the primary health issue that macrolid...,Which bacterial infection is particularly prob...,Select the items that are articles of clothing,What is one known effect of macrolide antibiot...,"According to the study, what was a finding reg...",Infections in their airways; Heart disease; Di...,Infections in their airways,Pseudomonas aeruginosa; Escherichia coli; Stre...,Pseudomonas aeruginosa,shirt; jeans; jacket,shirt; jeans; jacket,Slight improvement at six months; Deterioratio...,Slight improvement at six months,The risk was lower compared to placebo; The ri...,The risk was lower compared to placebo
541,1076,What is the primary health issue that macrolid...,Which bacterial infection is particularly prob...,Select all of the following that are colors,What is one known effect of macrolide antibiot...,"According to the study, what was a finding reg...",Infections in their airways; Heart disease; Di...,Infections in their airways,Pseudomonas aeruginosa; Escherichia coli; Stre...,Pseudomonas aeruginosa,blue; green; pink,blue; green; pink,Slight improvement at six months; Deterioratio...,Slight improvement at six months,The risk was lower compared to placebo; The ri...,The risk was lower compared to placebo

==============================
ABSTRACT ID: 1046
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
40,1046,What does the absence of data on secondary pre...,What was the primary focus of the review relat...,Select all of the following that are colors,What are examples of unhealthy dietary compone...,What dietary elements does the DASH diet focus...,The study provides comprehensive insights into...,It highlights a gap in understanding the DASH ...,Evaluating weight loss results; Preventing car...,Preventing cardiovascular diseases,blue; green; pink,blue; green; pink,"Sodium, red meat, sugar; Fruits and vegetables...","Sodium, red meat, sugar","Fruits, vegetables, whole grains, and lean pro...","Fruits, vegetables, whole grains, and lean pro..."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
379,1046,What does the absence of data on secondary pre...,What was the primary focus of the review relat...,Select the items that are articles of clothing,What are examples of unhealthy dietary compone...,What dietary elements does the DASH diet focus...,The study provides comprehensive insights into...,It highlights a gap in understanding the DASH ...,Evaluating weight loss results; Preventing car...,Preventing cardiovascular diseases,shirt; jeans; jacket,shirt; jeans; jacket,"Sodium, red meat, sugar; Fruits and vegetables...","Sodium, red meat, sugar","Fruits, vegetables, whole grains, and lean pro...","Fruits, vegetables, whole grains, and lean pro..."
740,1046,What does the absence of data on secondary pre...,What was the primary focus of the review relat...,Select all of the following that are colors,What are examples of unhealthy dietary compone...,What dietary elements does the DASH diet focus...,The study provides comprehensive insights into...,It highlights a gap in understanding the DASH ...,Evaluating weight loss results; Preventing car...,Preventing cardiovascular diseases,blue; green; pink,blue; green; pink,"Sodium, red meat, sugar; Fruits and vegetables...","Sodium, red meat, sugar","Fruits, vegetables, whole grains, and lean pro...","Fruits, vegetables, whole grains, and lean pro..."

==============================
ABSTRACT ID: 1105
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
94,1105,What factors should be considered to enhance t...,How might combining different school measures ...,Select all of the following that are colors,What are the implications of the knowledge gap...,What was the main goal of the measures impleme...,Focusing solely on quantitative studies; Explo...,Exploring unintended consequences across diver...,It could identify synergies and overlapping ef...,It could identify synergies and overlapping ef...,blue; green; pink,blue; green; pink,They suggest a need for diverse methodological...,They suggest a need for diverse methodological...,To stop the spread of the virus in school sett...,To stop the spread of the virus in school sett...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
397,1105,What factors should be considered to enhance t...,How might combining different school measures ...,Select the items that are articles of clothing,What are the implications of the knowledge gap...,What was the main goal of the measures impleme...,Focusing solely on quantitative studies; Explo...,Exploring unintended consequences across diver...,It could identify synergies and overlapping ef...,It could identify synergies and overlapping ef...,shirt; jeans; jacket,shirt; jeans; jacket,They suggest a need for diverse methodological...,They suggest a need for diverse methodological...,To stop the spread of the virus in school sett...,To stop the spread of the virus in school sett...
829,1105,What factors should be considered to enhance t...,How might combining different school measures ...,Select all of the following that are colors,What are the implications of the knowledge gap...,What was the main goal of the measures impleme...,Focusing solely on quantitative studies; Explo...,Exploring unintended consequences across diver...,It could identify synergies and overlapping ef...,It could identify synergies and overlapping ef...,blue; green; pink,blue; green; pink,They suggest a need for diverse methodological...,They suggest a need for diverse methodological...,To stop the spread of the virus in school sett...,To stop the spread of the virus in school sett...

==============================
ABSTRACT ID: 1106
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
95,1106,What reasoning could justify the conclusion th...,How might the design of future studies be impr...,Select the items that are animals,What conclusions might be drawn from the evide...,What challenges could arise in interpreting th...,No significant difference in hospitalisation r...,No significant difference in hospitalisation r...,Including a larger sample of hospitalised pati...,Including a larger sample of hospitalised pati...,Chair; Lamp; Dog,Dog,Viral clearance may not correlate directly wit...,Viral clearance may not correlate directly wit...,Lack of alignment between viral clearance and ...,Lack of alignment between viral clearance and ...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
406,1106,What reasoning could justify the conclusion th...,How might the design of future studies be impr...,Select the items that are articles of clothing,What conclusions might be drawn from the evide...,What challenges could arise in interpreting th...,No significant difference in hospitalisation r...,No significant difference in hospitalisation r...,Including a larger sample of hospitalised pati...,Including a larger sample of hospitalised pati...,shirt; jeans; jacket,shirt; jeans; jacket,Viral clearance may not correlate directly wit...,Viral clearance may not correlate directly wit...,Lack of alignment between viral clearance and ...,Lack of alignment between viral clearance and ...
631,1106,What reasoning could justify the conclusion th...,How might the design of future studies be impr...,Select the items that are animals,What conclusions might be drawn from the evide...,What challenges could arise in interpreting th...,No significant difference in hospitalisation r...,No significant difference in hospitalisation r...,Including a larger sample of hospitalised pati...,Including a larger sample of hospitalised pati...,Chair; Lamp; Dog,Dog,Viral clearance may not correlate directly wit...,Viral clearance may not correlate directly wit...,Lack of alignment between viral clearance and ...,Lack of alignment between viral clearance and ...

==============================
ABSTRACT ID: 1114
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
102,1114,Why is there uncertainty about recommending co...,In what ways can collaborative care enhance th...,Select the items that are animals,What are the common issues targeted by collabo...,How does collaborative care compare with routi...,The impact on very long-term outcomes is uncle...,The impact on very long-term outcomes is unclear.,By increasing the use of medication in line wi...,By increasing the use of medication in line wi...,Chair; Lamp; Dog,Dog,Depression and anxiety; Cardiovascular disease...,Depression and anxiety,Collaborative care is better at improving depr...,Collaborative care is better at improving depr...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
407,1114,Why is there uncertainty about recommending co...,In what ways can collaborative care enhance th...,Select the items that are animals,What are the common issues targeted by collabo...,How does collaborative care compare with routi...,The impact on very long-term outcomes is uncle...,The impact on very long-term outcomes is unclear.,By increasing the use of medication in line wi...,By increasing the use of medication in line wi...,Chair; Lamp; Dog,Dog,Depression and anxiety; Cardiovascular disease...,Depression and anxiety,Collaborative care is better at improving depr...,Collaborative care is better at improving depr...

==============================
ABSTRACT ID: 1044
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
38,1044,What conclusions can be drawn regarding the ef...,"In evaluating the safety profile of ezetimibe,...",Select the items that are animals,How does the study interpret the role of ezeti...,What is the impact of ezetimibe on blood lipid...,Ezetimibe with statins probably reduces the ri...,Ezetimibe with statins probably reduces the risk.,Evidence is insufficient to determine impact o...,Evidence is insufficient to determine impact o...,Chair; Lamp; Dog,Dog,Ezetimibe likely has little effect on heart-re...,Ezetimibe likely has little effect on heart-re...,It further reduces 'bad' cholesterol levels.; ...,It further reduces 'bad' cholesterol levels.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
424,1044,What conclusions can be drawn regarding the ef...,"In evaluating the safety profile of ezetimibe,...",Select the items that are animals,How does the study interpret the role of ezeti...,What is the impact of ezetimibe on blood lipid...,Ezetimibe with statins probably reduces the ri...,Ezetimibe with statins probably reduces the risk.,Evidence is insufficient to determine impact o...,Evidence is insufficient to determine impact o...,Chair; Lamp; Dog,Dog,Ezetimibe likely has little effect on heart-re...,Ezetimibe likely has little effect on heart-re...,It further reduces 'bad' cholesterol levels.; ...,It further reduces 'bad' cholesterol levels.

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1088
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
79,1088,What condition in children is associated with ...,What are some possible side effects of cortico...,Select all of the following that are colors,How does rituximab compare to a placebo in pre...,Which medication is believed to prolong remiss...,Nephrotic syndrome; Osteoporosis; Cataracts,Nephrotic syndrome,High blood pressure; Improved growth; Cataracts,High blood pressure; Cataracts,blue; green; pink,blue; green; pink,Probably reduces the risk of relapse; Has no e...,Probably reduces the risk of relapse,Mycophenolate mofetil; Levamisole; Cyclosporin,Mycophenolate mofetil

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
442,1088,What condition in children is associated with ...,What are some possible side effects of cortico...,Select all of the following that are fruits,How does rituximab compare to a placebo in pre...,Which medication is believed to prolong remiss...,Nephrotic syndrome; Osteoporosis; Cataracts,Nephrotic syndrome,High blood pressure; Improved growth; Cataracts,High blood pressure; Cataracts,dog; blue; grape,grape,Probably reduces the risk of relapse; Has no e...,Probably reduces the risk of relapse,Mycophenolate mofetil; Levamisole; Cyclosporin,Mycophenolate mofetil

==============================
ABSTRACT ID: 1001
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
0,1001,How might researchers justify the clinical rel...,What was the main aim of the review authors?,Select all of the following that are fruits,Which outcome did exercise improve in type 2 d...,What was a significant effect of exercise iden...,Improvements in insulin response and decreased...,Improvements in insulin response and decreased...,To determine the effect of exercise on blood s...,To determine the effect of exercise on blood s...,dog; blue; grape,grape,Blood sugar control; Blood cholesterol levels;...,Blood sugar control,Decreased body fat content; Increased overall ...,Decreased body fat content

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
451,1001,How might researchers justify the clinical rel...,What was the main aim of the review authors?,Select all of the following that are fruits,Which outcome did exercise improve in type 2 d...,What was a significant effect of exercise iden...,Improvements in insulin response and decreased...,Improvements in insulin response and decreased...,To determine the effect of exercise on blood s...,To determine the effect of exercise on blood s...,dog; blue; grape,grape,Blood sugar control; Blood cholesterol levels;...,Blood sugar control,Decreased body fat content; Increased overall ...,Decreased body fat content

==============================
ABSTRACT ID: 1018
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
14,1018,In what way do biosimilars demonstrate their t...,How could a decision-maker justify the use of ...,Select all of the following that are colors,Name the three monoclonal antibodies mentioned...,Describe the types of cancer involved in the s...,By showing adequately similar outcomes in crit...,By showing adequately similar outcomes in crit...,By arguing that biosimilars provide a moderate...,By highlighting their overall similar effectiv...,blue; green; pink,blue; green; pink,Bevacizumab; Rituximab; Trastuzumab,Bevacizumab; Rituximab; Trastuzumab,"Lung, colorectal, non-Hodgkin's lymphoma, and ...","Lung, colorectal, non-Hodgkin's lymphoma, and ..."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
470,1018,In what way do biosimilars demonstrate their t...,How could a decision-maker justify the use of ...,Select the items that are animals,Name the three monoclonal antibodies mentioned...,Describe the types of cancer involved in the s...,By showing adequately similar outcomes in crit...,By showing adequately similar outcomes in crit...,By arguing that biosimilars provide a moderate...,By highlighting their overall similar effectiv...,Chair; Lamp; Dog,Dog,Bevacizumab; Rituximab; Trastuzumab,Bevacizumab; Rituximab; Trastuzumab,"Lung, colorectal, non-Hodgkin's lymphoma, and ...","Lung, colorectal, non-Hodgkin's lymphoma, and ..."

==============================
ABSTRACT ID: 1011
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
8,1011,In what ways could the lack of reported diabet...,What was the primary objective of the study?,Select all of the following that are fruits,Describe the effect of diet plus physical acti...,Identify the outcomes that were not conclusive...,It may limit understanding of the full benefit...,It may limit understanding of the full benefit...,Investigate whether diet and physical activity...,Investigate whether diet and physical activity...,dog; blue; grape,grape,It decreased the risk of developing type 2 dia...,It decreased the risk of developing type 2 dia...,Health-related quality of life.; Blood glucose...,Health-related quality of life.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
487,1011,In what ways could the lack of reported diabet...,What was the primary objective of the study?,Select all of the following that are fruits,Describe the effect of diet plus physical acti...,Identify the outcomes that were not conclusive...,It may limit understanding of the full benefit...,It may limit understanding of the full benefit...,Investigate whether diet and physical activity...,Investigate whether diet and physical activity...,dog; blue; grape,grape,It decreased the risk of developing type 2 dia...,It decreased the risk of developing type 2 dia...,Health-related quality of life.; Blood glucose...,Health-related quality of life.

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1102
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
91,1102,What changes would improve the overall confide...,What criteria were used to include studies in ...,Select the items that are animals,Describe the impact of combined dietary and ac...,Explain the significance of implementing strat...,More consistent data reporting; Broader geogra...,More consistent data reporting; Broader geogra...,Strategies aimed at changing children's diet o...,Strategies aimed at changing children's diet o...,Chair; Lamp; Dog,Dog,They may slightly reduce BMI.; They have no ef...,They may slightly reduce BMI.,They help minimize excess weight gain.; They e...,They help minimize excess weight gain.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
505,1102,What changes would improve the overall confide...,What criteria were used to include studies in ...,Select the items that are animals,Describe the impact of combined dietary and ac...,Explain the significance of implementing strat...,More consistent data reporting; Broader geogra...,More consistent data reporting; Broader geogra...,Strategies aimed at changing children's diet o...,Strategies aimed at changing children's diet o...,Chair; Lamp; Dog,Dog,They may slightly reduce BMI.; They have no ef...,They may slightly reduce BMI.,They help minimize excess weight gain.; They e...,They help minimize excess weight gain.

==============================
ABSTRACT ID: 1016
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
13,1016,How do the study results challenge the potenti...,What was a key motivation for the study?,Select all of the following that are colors,What was the outcome of using a mouth spray wi...,"In the study, how did artificial cannabinoids ...",There is no strong evidence that CbMs offer su...,There is no strong evidence that CbMs offer su...,To determine the effectiveness of CbMs in canc...,To determine the effectiveness of CbMs in canc...,blue; green; pink,blue; green; pink,It was more effective than placebo.; It did no...,It did not show significant improvement over p...,They were superior in reducing pain.; They sho...,They showed no difference in pain reduction.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
506,1016,How do the study results challenge the potenti...,What was a key motivation for the study?,Select all of the following that are colors,What was the outcome of using a mouth spray wi...,"In the study, how did artificial cannabinoids ...",There is no strong evidence that CbMs offer su...,There is no strong evidence that CbMs offer su...,To determine the effectiveness of CbMs in canc...,To determine the effectiveness of CbMs in canc...,blue; green; pink,blue; green; pink,It was more effective than placebo.; It did no...,It did not show significant improvement over p...,They were superior in reducing pain.; They sho...,They showed no difference in pain reduction.

==============================
ABSTRACT ID: 1113
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
101,1113,What might be the reasons for conducting an up...,How can the effectiveness of music therapy com...,Select all of the following that are colors,What conclusions can be drawn about the types ...,Summarize the effect of music therapy when add...,To assess if music therapy has become more eff...,To assess if music therapy has become more eff...,By considering the large sample size of the st...,By acknowledging the uncertainty due to small ...,blue; green; pink,blue; green; pink,Active music therapy was found superior to rec...,There is insufficient evidence to determine if...,It reduces depressive symptoms; It has no effe...,It reduces depressive symptoms; It improves da...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
514,1113,What might be the reasons for conducting an up...,How can the effectiveness of music therapy com...,Select the items that are articles of clothing,What conclusions can be drawn about the types ...,Summarize the effect of music therapy when add...,To assess if music therapy has become more eff...,To assess if music therapy has become more eff...,By considering the large sample size of the st...,By acknowledging the uncertainty due to small ...,shirt; jeans; jacket,shirt; jeans; jacket,Active music therapy was found superior to rec...,There is insufficient evidence to determine if...,It reduces depressive symptoms; It has no effe...,It reduces depressive symptoms; It improves da...
614,1113,What might be the reasons for conducting an up...,How can the effectiveness of music therapy com...,Select all of the following that are colors,What conclusions can be drawn about the types ...,Summarize the effect of music therapy when add...,To assess if music therapy has become more eff...,To assess if music therapy has become more eff...,By considering the large sample size of the st...,By acknowledging the uncertainty due to small ...,blue; green; pink,blue; green; pink,Active music therapy was found superior to rec...,There is insufficient evidence to determine if...,It reduces depressive symptoms; It has no effe...,It reduces depressive symptoms; It improves da...
649,1113,What might be the reasons for conducting an up...,How can the effectiveness of music therapy com...,Select the items that are animals,What conclusions can be drawn about the types ...,Summarize the effect of music therapy when add...,To assess if music therapy has become more eff...,To assess if music therapy has become more eff...,By considering the large sample size of the st...,By acknowledging the uncertainty due to small ...,Chair; Lamp; Dog,Dog,Active music therapy was found superior to rec...,There is insufficient evidence to determine if...,It reduces depressive symptoms; It has no effe...,It reduces depressive symptoms; It improves da...

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

==============================
ABSTRACT ID: 1037
EXPECTED (from abstracts_df):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
32,1037,What factors might contribute to the low quali...,To what extent does commercial sponsorship imp...,Select all of the following that are colors,What did bone marrow stem/progenitor cells sho...,What is necessary to confirm the results found...,Limited number of studies and participants; Hi...,Limited number of studies and participants; Pr...,It may introduce bias and affect the perceived...,It may introduce bias and affect the perceived...,blue; green; pink,blue; green; pink,Chronic ischaemic heart disease and heart fail...,Chronic ischaemic heart disease and heart failure,Further research with larger sample sizes; An ...,Further research with larger sample sizes

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
515,1037,What factors might contribute to the low quali...,To what extent does commercial sponsorship imp...,Select all of the following that are colors,What did bone marrow stem/progenitor cells sho...,What is necessary to confirm the results found...,Limited number of studies and participants; Hi...,Limited number of studies and participants; Pr...,It may introduce bias and affect the perceived...,It may introduce bias and affect the perceived...,blue; green; pink,blue; green; pink,Chronic ischaemic heart disease and heart fail...,Chronic ischaemic heart disease and heart failure,Further research with larger sample sizes; An ...,Further research with larger sample sizes

==============================
ABSTRACT ID: 1131
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
116,1131,What key limitations in the studies may have i...,Why might the biological mechanism of statins ...,Select all of the following that are colors,Summarize the conclusion about the effect of s...,Explain the proposed relationship between chol...,The methods of cognition assessment used; The ...,The methods of cognition assessment used; The ...,Statins are known for their cholesterol-reduci...,Statins are known for their cholesterol-reduci...,blue; green; pink,blue; green; pink,Statins do not prevent cognitive decline; Stat...,Statins do not prevent cognitive decline,High cholesterol may increase dementia risk; L...,High cholesterol may increase dementia risk

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
532,1131,What key limitations in the studies may have i...,Why might the biological mechanism of statins ...,Select all of the following that are colors,Summarize the conclusion about the effect of s...,Explain the proposed relationship between chol...,The methods of cognition assessment used; The ...,The methods of cognition assessment used; The ...,Statins are known for their cholesterol-reduci...,Statins are known for their cholesterol-reduci...,blue; green; pink,blue; green; pink,Statins do not prevent cognitive decline; Stat...,Statins do not prevent cognitive decline,High cholesterol may increase dementia risk; L...,High cholesterol may increase dementia risk

==============================
ABSTRACT ID: 1099
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
88,1099,What are the implications of the study's limit...,In what ways might further independent studies...,Select all of the following that are fruits,Describe the main comparison made in the semag...,Explain the effects of semaglutide on weight l...,It restricts the applicability of results to d...,It restricts the applicability of results to d...,They can provide insights into long-term side ...,They can provide insights into long-term side ...,dog; blue; grape,grape,Semaglutide was compared with a placebo; Semag...,Semaglutide was compared with a placebo,Semaglutide leads to more weight loss than pla...,Semaglutide leads to more weight loss than pla...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
542,1099,What are the implications of the study's limit...,In what ways might further independent studies...,Select all of the following that are fruits,Describe the main comparison made in the semag...,Explain the effects of semaglutide on weight l...,It restricts the applicability of results to d...,It restricts the applicability of results to d...,They can provide insights into long-term side ...,They can provide insights into long-term side ...,dog; blue; grape,grape,Semaglutide was compared with a placebo; Semag...,Semaglutide was compared with a placebo,Semaglutide leads to more weight loss than pla...,Semaglutide leads to more weight loss than pla...

==============================
ABSTRACT ID: 1059
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
51,1059,What factors might have contributed to the low...,Identify the main goal of the study discussed ...,Select all of the following that are colors,Summarize why seat belt laws alone are insuffi...,Recognize the types of interventions evaluated...,Inconsistencies in definitions of seat belt us...,Differences in intervention effectiveness acro...,To determine the most effective seat belt laws...,To evaluate interventions that promote seat be...,blue; green; pink,blue; green; pink,Laws alone do not guarantee behavior change.; ...,Laws alone do not guarantee behavior change.,"Educational, incentive, and engineering-based....","Educational, incentive, and engineering-based."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
550,1059,What factors might have contributed to the low...,Identify the main goal of the study discussed ...,Select all of the following that are colors,Summarize why seat belt laws alone are insuffi...,Recognize the types of interventions evaluated...,Inconsistencies in definitions of seat belt us...,Differences in intervention effectiveness acro...,To determine the most effective seat belt laws...,To evaluate interventions that promote seat be...,blue; green; pink,blue; green; pink,Laws alone do not guarantee behavior change.; ...,Laws alone do not guarantee behavior change.,"Educational, incentive, and engineering-based....","Educational, incentive, and engineering-based."

==============================
ABSTRACT ID: 1124
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
109,1124,What are the implications of case management i...,How does the variability in case management im...,Select all of the following that are colors,In what manner could the study's methodology b...,What differences were observed in the effectiv...,They consistently reduce overall healthcare co...,"They show mixed results, with some indication ...",It creates challenges in measuring consistent ...,It creates challenges in measuring consistent ...,blue; green; pink,blue; green; pink,By incorporating a larger number of RCTs focus...,By incorporating a larger number of RCTs focus...,Significant differences in institutionalizatio...,Significant differences in institutionalizatio...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
560,1124,What are the implications of case management i...,How does the variability in case management im...,Select all of the following that are colors,In what manner could the study's methodology b...,What differences were observed in the effectiv...,They consistently reduce overall healthcare co...,"They show mixed results, with some indication ...",It creates challenges in measuring consistent ...,It creates challenges in measuring consistent ...,blue; green; pink,blue; green; pink,By incorporating a larger number of RCTs focus...,By incorporating a larger number of RCTs focus...,Significant differences in institutionalizatio...,Significant differences in institutionalizatio...

==============================
ABSTRACT ID: 1083
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
74,1083,In analyzing the motivations behind evaluating...,What technologies were included in the eHealth...,Select all of the following that are colors,Summarize the main outcome of using eHealth in...,What does the study suggest about the current ...,Improved self-management skills; Immediate imp...,Improved self-management skills; Enhanced heal...,Telehealth; Invasive surgical tools; Electroni...,Telehealth; Electronic monitors,blue; green; pink,blue; green; pink,Uncertain impact on improving outcomes; Defini...,Uncertain impact on improving outcomes,Low quality and uncertain effects; High qualit...,Low quality and uncertain effects

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
577,1083,In analyzing the motivations behind evaluating...,What technologies were included in the eHealth...,Select the items that are articles of clothing,Summarize the main outcome of using eHealth in...,What does the study suggest about the current ...,Improved self-management skills; Immediate imp...,Improved self-management skills; Enhanced heal...,Telehealth; Invasive surgical tools; Electroni...,Telehealth; Electronic monitors,shirt; jeans; jacket,shirt; jeans; jacket,Uncertain impact on improving outcomes; Defini...,Uncertain impact on improving outcomes,Low quality and uncertain effects; High qualit...,Low quality and uncertain effects

==============================
ABSTRACT ID: 1064
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
56,1064,What are the main types of stroke mentioned in...,Summarize the primary goal of the study about ...,Select all of the following that are colors,Identify adverse events associated with oral e...,Describe the types of nutritional therapy inte...,Ischaemic stroke; Cardiac stroke; Haemorrhagic...,Ischaemic stroke; Haemorrhagic stroke,To reduce disability and improve daily activit...,To reduce disability and improve daily activities,blue; green; pink,blue; green; pink,Diarrhoea; Increased walking speed; Either hyp...,Diarrhoea; Either hyperglycaemia or hypoglycaemia,Nutrients for daily and between meal care; Psy...,Nutrients for daily and between meal care

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
578,1064,What are the main types of stroke mentioned in...,Summarize the primary goal of the study about ...,Select all of the following that are colors,Identify adverse events associated with oral e...,Describe the types of nutritional therapy inte...,Ischaemic stroke; Cardiac stroke; Haemorrhagic...,Ischaemic stroke; Haemorrhagic stroke,To reduce disability and improve daily activit...,To reduce disability and improve daily activities,blue; green; pink,blue; green; pink,Diarrhoea; Increased walking speed; Either hyp...,Diarrhoea; Either hyperglycaemia or hypoglycaemia,Nutrients for daily and between meal care; Psy...,Nutrients for daily and between meal care

==============================
ABSTRACT ID: 1079
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
70,1079,How do the study findings relate to the previo...,What was the primary aim of the study regardin...,Select all of the following that are colors,Identify which group was underrepresented in t...,Summarize the overall findings of the study re...,The updated review confirmed the previous revi...,The updated review contradicted the previous r...,To assess the impact on severe asthma attacks....,To assess the impact on severe asthma attacks.,blue; green; pink,blue; green; pink,People with severe asthma.; People with high b...,People with severe asthma.,It had no significant effect on asthma control...,It had no significant effect on asthma control.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
586,1079,How do the study findings relate to the previo...,What was the primary aim of the study regardin...,Select the items that are articles of clothing,Identify which group was underrepresented in t...,Summarize the overall findings of the study re...,The updated review confirmed the previous revi...,The updated review contradicted the previous r...,To assess the impact on severe asthma attacks....,To assess the impact on severe asthma attacks.,shirt; jeans; jacket,shirt; jeans; jacket,People with severe asthma.; People with high b...,People with severe asthma.,It had no significant effect on asthma control...,It had no significant effect on asthma control.

==============================
ABSTRACT ID: 1132
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
117,1132,What could be the implications of the study's ...,In what ways do the limitations of these studi...,Select all of the following that are colors,Identify the primary goal of the study regardi...,Summarize the main finding of the aspirin stud...,Future studies will likely focus on alternativ...,Future studies will likely focus on alternativ...,The limitations significantly weaken the evide...,The limitations significantly weaken the evide...,blue; green; pink,blue; green; pink,To observe their effectiveness in delaying or ...,To observe their effectiveness in delaying or ...,No evidence was found to support the use of as...,No evidence was found to support the use of as...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
587,1132,What could be the implications of the study's ...,In what ways do the limitations of these studi...,Select all of the following that are colors,Identify the primary goal of the study regardi...,Summarize the main finding of the aspirin stud...,Future studies will likely focus on alternativ...,Future studies will likely focus on alternativ...,The limitations significantly weaken the evide...,The limitations significantly weaken the evide...,blue; green; pink,blue; green; pink,To observe their effectiveness in delaying or ...,To observe their effectiveness in delaying or ...,No evidence was found to support the use of as...,No evidence was found to support the use of as...

==============================
ABSTRACT ID: 1027
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
23,1027,How do the results of tamoxifen compare to aro...,Evaluate the implications of raloxifene's lowe...,Select the items that are animals,What was the main goal of the Cochrane Review ...,Which side effects were more prevalent in wome...,Aromatase inhibitors reduced the risk more tha...,Aromatase inhibitors reduced the risk more tha...,Raloxifene is less effective but has fewer sid...,Raloxifene is less effective but has fewer sid...,Chair; Lamp; Dog,Dog,To summarize evidence on the efficacy and toxi...,To summarize evidence on the efficacy and toxi...,Higher incidence of endometrial cancer and thr...,Higher incidence of endometrial cancer and thr...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
604,1027,How do the results of tamoxifen compare to aro...,Evaluate the implications of raloxifene's lowe...,Select the items that are animals,What was the main goal of the Cochrane Review ...,Which side effects were more prevalent in wome...,Aromatase inhibitors reduced the risk more tha...,Aromatase inhibitors reduced the risk more tha...,Raloxifene is less effective but has fewer sid...,Raloxifene is less effective but has fewer sid...,Chair; Lamp; Dog,Dog,To summarize evidence on the efficacy and toxi...,To summarize evidence on the efficacy and toxi...,Higher incidence of endometrial cancer and thr...,Higher incidence of endometrial cancer and thr...

==============================
ABSTRACT ID: 1073
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
65,1073,What was the main goal of the study?,Which condition was primarily targeted in the ...,Select the items that are animals,What did the study evaluate about IMT combined...,Explain the difference between IMT alone and c...,To determine if IMT reduces breathlessness.; T...,To determine if IMT reduces breathlessness.,Chronic obstructive pulmonary disease (COPD).;...,Chronic obstructive pulmonary disease (COPD).,Chair; Lamp; Dog,Dog,"Improvement in breathlessness, physical fitnes...","Improvement in breathlessness, physical fitnes...",IMT alone may improve breathlessness and fitne...,IMT alone may improve breathlessness and fitne...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
613,1073,What was the main goal of the study?,Which condition was primarily targeted in the ...,Select the items that are animals,What did the study evaluate about IMT combined...,Explain the difference between IMT alone and c...,To determine if IMT reduces breathlessness.; T...,To determine if IMT reduces breathlessness.,Chronic obstructive pulmonary disease (COPD).;...,Chronic obstructive pulmonary disease (COPD).,Chair; Lamp; Dog,Dog,"Improvement in breathlessness, physical fitnes...","Improvement in breathlessness, physical fitnes...",IMT alone may improve breathlessness and fitne...,IMT alone may improve breathlessness and fitne...

==============================
ABSTRACT ID: 1068
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
60,1068,What was the primary motivation for the study?,What outcome was observed with adding clopidog...,Select all of the following that are colors,Which adverse effect was noted when combining ...,NaN,To assess whether adding clopidogrel to aspiri...,To assess whether adding clopidogrel to aspiri...,Reduced risk of heart attack or stroke.; Incre...,Reduced risk of heart attack or stroke.,blue; green; pink,blue; green; pink,Higher risk of major and minor bleeding.; Incr...,Higher risk of major and minor bleeding.,NaN,NaN

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
659,1068,What was the primary motivation for the study?,What outcome was observed with adding clopidog...,Select all of the following that are colors,Which adverse effect was noted when combining ...,NaN,To assess whether adding clopidogrel to aspiri...,To assess whether adding clopidogrel to aspiri...,Reduced risk of heart attack or stroke.; Incre...,Reduced risk of heart attack or stroke.,blue; green; pink,blue; green; pink,Higher risk of major and minor bleeding.; Incr...,Higher risk of major and minor bleeding.,NaN,NaN

==============================
ABSTRACT ID: 1031
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
27,1031,How do the latest findings on exercise-based c...,What is the primary aim of exercise-based card...,Select the items that are animals,How does exercise-based CR affect the risk of ...,What type of exercise is most commonly include...,They demonstrate a reduction in cardiovascular...,They demonstrate a reduction in cardiovascular...,To improve health and outcomes; To increase ho...,To improve health and outcomes,Chair; Lamp; Dog,Dog,Reduces hospital admission risk; Increases hos...,Reduces hospital admission risk,Swimming; Stationary cycling; Weightlifting,Stationary cycling

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
667,1031,How do the latest findings on exercise-based c...,What is the primary aim of exercise-based card...,Select the items that are animals,How does exercise-based CR affect the risk of ...,What type of exercise is most commonly include...,They demonstrate a reduction in cardiovascular...,They demonstrate a reduction in cardiovascular...,To improve health and outcomes; To increase ho...,To improve health and outcomes,Chair; Lamp; Dog,Dog,Reduces hospital admission risk; Increases hos...,Reduces hospital admission risk,Swimming; Stationary cycling; Weightlifting,Stationary cycling

==============================
ABSTRACT ID: 1069
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
61,1069,What is the primary goal of remote ischaemic c...,What effects of RIC on brain function issues w...,Select the items that are animals,How does RIC compare to sham or standard treat...,What was evaluated alongside the benefits of R...,To dissolve existing blood clots in the brain....,To trigger the body's natural defenses to prot...,RIC might result in a slight improvement in br...,RIC might result in a slight improvement in br...,Chair; Lamp; Dog,Dog,RIC probably leads to a slight reduction in th...,RIC probably leads to a slight reduction in th...,The harms of RIC were also evaluated.; Only th...,The harms of RIC were also evaluated.

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
677,1069,What is the primary goal of remote ischaemic c...,What effects of RIC on brain function issues w...,Select the items that are animals,How does RIC compare to sham or standard treat...,What was evaluated alongside the benefits of R...,To dissolve existing blood clots in the brain....,To trigger the body's natural defenses to prot...,RIC might result in a slight improvement in br...,RIC might result in a slight improvement in br...,Chair; Lamp; Dog,Dog,RIC probably leads to a slight reduction in th...,RIC probably leads to a slight reduction in th...,The harms of RIC were also evaluated.; Only th...,The harms of RIC were also evaluated.

==============================
ABSTRACT ID: 1082
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
73,1082,Which factors may influence the validity of th...,What criteria were used to determine the study...,Select all of the following that are fruits,Evaluate the potential limitations of the stud...,What effect do education programmes have on se...,Variability in programme design and delivery.;...,Variability in programme design and delivery.;...,Study methods and sizes.; Geographic diversity...,Study methods and sizes.,dog; blue; grape,grape,Limited number of studies and participants.; I...,Limited number of studies and participants.; V...,They may improve confidence in home blood suga...,They may improve confidence in home blood suga...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
739,1082,Which factors may influence the validity of th...,What criteria were used to determine the study...,Select all of the following that are fruits,Evaluate the potential limitations of the stud...,What effect do education programmes have on se...,Variability in programme design and delivery.;...,Variability in programme design and delivery.;...,Study methods and sizes.; Geographic diversity...,Study methods and sizes.,dog; blue; grape,grape,Limited number of studies and participants.; I...,Limited number of studies and participants.; V...,They may improve confidence in home blood suga...,They may improve confidence in home blood suga...

==============================
ABSTRACT ID: 1126
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
111,1126,What were the primary motivations for conducti...,"In evaluating the results of the study, what w...",Select all of the following that are fruits,What conclusions can be drawn about the clinic...,What potential limitations in the study proces...,To find a cure for Alzheimer's disease.; To as...,To assess galantamine's effectiveness on sympt...,Galantamine substantially improved memory and ...,Galantamine had little to no effect on memory ...,dog; blue; grape,grape,The memory improvements were minor and not cli...,Galantamine led to clinically meaningful impro...,The high dropout rate among participants recei...,The high dropout rate among participants recei...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
757,1126,What were the primary motivations for conducti...,"In evaluating the results of the study, what w...",Select all of the following that are fruits,What conclusions can be drawn about the clinic...,What potential limitations in the study proces...,To find a cure for Alzheimer's disease.; To as...,To assess galantamine's effectiveness on sympt...,Galantamine substantially improved memory and ...,Galantamine had little to no effect on memory ...,dog; blue; grape,grape,The memory improvements were minor and not cli...,Galantamine led to clinically meaningful impro...,The high dropout rate among participants recei...,The high dropout rate among participants recei...

==============================
ABSTRACT ID: 1042
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
36,1042,What are potential risks associated with using...,What was the primary motivation for comparing ...,Select all of the following that are colors,What outcome did the review find regarding the...,Which aspect related to postoperative recovery...,Increased complexity of heart visibility and a...,Increased complexity of heart visibility and a...,To determine if visibility was improved; To as...,To assess safety and effectiveness,blue; green; pink,blue; green; pink,There is a significant decrease in mortality w...,There is possibly no difference in mortality,Postoperative pain levels; Blood loss; Quality...,Blood loss

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
811,1042,What are potential risks associated with using...,What was the primary motivation for comparing ...,Select all of the following that are colors,What outcome did the review find regarding the...,Which aspect related to postoperative recovery...,Increased complexity of heart visibility and a...,Increased complexity of heart visibility and a...,To determine if visibility was improved; To as...,To assess safety and effectiveness,blue; green; pink,blue; green; pink,There is a significant decrease in mortality w...,There is possibly no difference in mortality,Postoperative pain levels; Blood loss; Quality...,Blood loss

==============================
ABSTRACT ID: 1096
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
85,1096,What are the primary motivations for conductin...,How could the findings of this review affect f...,Select all of the following that are colors,How should the potential for systematic or ran...,What did the trials compare bezafibrate with?,To consolidate existing evidence from scattere...,To consolidate existing evidence from scattere...,By discouraging further trials on bezafibrate;...,By highlighting the need for rigorously conduc...,blue; green; pink,blue; green; pink,It should be considered as a major limitation ...,It should be considered as a major limitation ...,No intervention and ursodeoxycholic acid; Plac...,No intervention and ursodeoxycholic acid

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
856,1096,What are the primary motivations for conductin...,How could the findings of this review affect f...,Select all of the following that are colors,How should the potential for systematic or ran...,What did the trials compare bezafibrate with?,To consolidate existing evidence from scattere...,To consolidate existing evidence from scattere...,By discouraging further trials on bezafibrate;...,By highlighting the need for rigorously conduc...,blue; green; pink,blue; green; pink,It should be considered as a major limitation ...,It should be considered as a major limitation ...,No intervention and ursodeoxycholic acid; Plac...,No intervention and ursodeoxycholic acid
910,1096,What are the primary motivations for conductin...,How could the findings of this review affect f...,Select the items that are articles of clothing,How should the potential for systematic or ran...,What did the trials compare bezafibrate with?,To consolidate existing evidence from scattere...,To consolidate existing evidence from scattere...,By discouraging further trials on bezafibrate;...,By highlighting the need for rigorously conduc...,shirt; jeans; jacket,shirt; jeans; jacket,It should be considered as a major limitation ...,It should be considered as a major limitation ...,No intervention and ursodeoxycholic acid; Plac...,No intervention and ursodeoxycholic acid

==============================
ABSTRACT ID: 1127
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
112,1127,What motivations likely influenced the researc...,In evaluating the effects of different doses o...,Select all of the following that are colors,What are the potential limitations in interpre...,Judge the appropriateness of using donepezil a...,The prevalence of acetylcholinesterase inhibit...,The prevalence of acetylcholinesterase inhibit...,Cognitive function improvements.; Comparison o...,Cognitive function improvements.; Comparison o...,blue; green; pink,blue; green; pink,Evidence based mainly on short-term studies.; ...,Evidence based mainly on short-term studies.; ...,Appropriate due to measurable benefits in cogn...,Appropriate due to measurable benefits in cogn...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
884,1127,What motivations likely influenced the researc...,In evaluating the effects of different doses o...,Select all of the following that are colors,What are the potential limitations in interpre...,Judge the appropriateness of using donepezil a...,The prevalence of acetylcholinesterase inhibit...,The prevalence of acetylcholinesterase inhibit...,Cognitive function improvements.; Comparison o...,Cognitive function improvements.; Comparison o...,blue; green; pink,blue; green; pink,Evidence based mainly on short-term studies.; ...,Evidence based mainly on short-term studies.; ...,Appropriate due to measurable benefits in cogn...,Appropriate due to measurable benefits in cogn...

==============================
ABSTRACT ID: 1002
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
1,1002,How do various quality improvement strategies ...,What hypothesis can be generated about the rel...,Select all of the following that are colors,Critique the role of patient education among t...,Which strategies were part of the three most e...,Strategies involving patient education and cas...,Strategies involving patient education and cas...,Multicomponent strategies may lead to populati...,Multicomponent strategies may lead to populati...,blue; green; pink,blue; green; pink,Patient education is essential but must be com...,Patient education is essential but must be com...,"Case management, team changes, promotion of se...","Case management, team changes, promotion of se..."

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
892,1002,How do various quality improvement strategies ...,What hypothesis can be generated about the rel...,Select all of the following that are colors,Critique the role of patient education among t...,Which strategies were part of the three most e...,Strategies involving patient education and cas...,Strategies involving patient education and cas...,Multicomponent strategies may lead to populati...,Multicomponent strategies may lead to populati...,blue; green; pink,blue; green; pink,Patient education is essential but must be com...,Patient education is essential but must be com...,"Case management, team changes, promotion of se...","Case management, team changes, promotion of se..."

==============================
ABSTRACT ID: 1101
EXPECTED (from abstracts_df):

C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())
C:\Users\ercj\AppData\Local\Temp\1\ipykernel_38688\2891837978.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(lambda x: "" if pd.isna(x) else str(x).strip())

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
90,1101,Which factors might influence the effectivenes...,How could future research improve the understa...,Select all of the following that are colors,What conclusions can be drawn regarding the im...,What modifications could enhance the reliabili...,The design and conduct of the studies; The inv...,The design and conduct of the studies; The inv...,By including a wider range of demographic grou...,By including a wider range of demographic grou...,blue; green; pink,blue; green; pink,Its long-term effects on major cardiovascular ...,Its long-term effects on major cardiovascular ...,Conducting studies independently from the drug...,Conducting studies independently from the drug...

ACTUAL UNIQUE ROWS (from final_df static_2):

,abstract_id,question_1,question_2,question_3,question_4,question_5,question_1_answers_choices,question_1_correct_answers,question_2_answers_choices,question_2_correct_answers,question_3_answers_choices,question_3_correct_answers,question_4_answers_choices,question_4_correct_answers,question_5_answers_choices,question_5_correct_answers
938,1101,Which factors might influence the effectivenes...,How could future research improve the understa...,Select all of the following that are colors,What conclusions can be drawn regarding the im...,What modifications could enhance the reliabili...,The design and conduct of the studies; The inv...,The design and conduct of the studies; The inv...,By including a wider range of demographic grou...,By including a wider range of demographic grou...,blue; green; pink,blue; green; pink,Its long-term effects on major cardiovascular ...,Its long-term effects on major cardiovascular ...,Conducting studies independently from the drug...,Conducting studies independently from the drug...